# ResNet50 + Transfer Learning para PetFinder AdoptionSpeed

Notebook trabajado en Kaggle con GPU.

Se desarrolla un modelo de clasificación de imágenes para predecir la velocidad de adopción de mascotas utilizando redes neuronales convolucionales preentrenadas.

Se evalúan distintas configuraciones de entrenamiento considerando:
- Capas entrenadas (FC vs fine-tuning)
- Tamaño de batch
- Learning rate
- Número de epochs

El desempeño se mide mediante Quadratic Weighted Kappa (QWK).

## 1. Instalación de dependencias

Se instala Optuna para realizar la búsqueda de hiperparámetros.  
El resto de las librerías utilizadas ya se encuentran disponibles en el entorno de Kaggle.

In [2]:
!pip install optuna -q

## 2. Imports

In [12]:
import os
import shutil
import time
import copy
import datetime
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, cohen_kappa_score

import optuna

import torch
import torchvision.models as models
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms

from joblib import dump, load

## 3. Configuración del entorno de cómputo

Se verifica la disponibilidad de GPU en Kaggle y se define el dispositivo de entrenamiento.

In [13]:
print("CUDA disponible:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

CUDA disponible: True
GPU: Tesla T4
Device: cuda

## 4. Rutas del dataset en Kaggle

El dataset fue agregado al notebook desde la competencia **PetFinder Adoption Prediction**.  
En Kaggle, los datos de entrada se encuentran en `/kaggle/input`, mientras que los archivos generados durante la ejecución se guardan en `/kaggle/working`.

In [14]:
INPUT_DIR = "/kaggle/input"
WORKING_DIR = "/kaggle/working"

print("Contenido de /kaggle/input:")
print(os.listdir(INPUT_DIR))

print("Contenido de /kaggle/working:")
print(os.listdir(WORKING_DIR))

Contenido de /kaggle/input:
['competitions']
Contenido de /kaggle/working:
['.virtual_documents']

In [15]:
DATA_DIR = "/kaggle/input/competitions/petfinder-adoption-prediction"
WORK_DIR = "/kaggle/working"

TRAIN_CSV = f"{DATA_DIR}/train/train.csv"
TEST_CSV = f"{DATA_DIR}/test/test.csv"

TRAIN_IMG_DIR = f"{DATA_DIR}/train_images"
TEST_IMG_DIR = f"{DATA_DIR}/test_images"

TRAIN_META_DIR = f"{DATA_DIR}/train_metadata"
TEST_META_DIR = f"{DATA_DIR}/test_metadata"

TRAIN_SENTIMENT_DIR = f"{DATA_DIR}/train_sentiment"
TEST_SENTIMENT_DIR = f"{DATA_DIR}/test_sentiment"

BREED_LABELS = f"{DATA_DIR}/breed_labels.csv"
COLOR_LABELS = f"{DATA_DIR}/color_labels.csv"
STATE_LABELS = f"{DATA_DIR}/state_labels.csv"

## 5. Carga inicial del archivo train.csv

Se carga la tabla principal de entrenamiento.  
Cada fila representa una mascota e incluye variables descriptivas, el identificador `PetID` y la variable objetivo `AdoptionSpeed`.

In [16]:
df_train = pd.read_csv(TRAIN_CSV)

print(df_train.shape)
df_train.head()

(14993, 24)

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,...,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,...,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,...,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,...,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,...,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

## 6. Paths y parámetros generales

Se definen las rutas de trabajo, carpetas para guardar modelos, matrices de confusión y resultados de Optuna.  
También se fijan parámetros generales del entrenamiento.

In [17]:
DATA_DIR = "/kaggle/input/competitions/petfinder-adoption-prediction"
WORK_DIR = "/kaggle/working"

PATH_TO_TRAIN = f"{DATA_DIR}/train/train.csv"
PATH_TO_IMAGES_DIR = f"{DATA_DIR}/train_images"

PATH_TO_WORK = WORK_DIR
PATH_TO_TEMP_FILES = os.path.join(PATH_TO_WORK, "optuna_temp_artifacts")
PATH_TO_OPTUNA_ARTIFACTS = os.path.join(PATH_TO_WORK, "optuna_artifacts")
PATH_TO_MODELS = os.path.join(PATH_TO_WORK, "models")
PATH_TO_CMS = os.path.join(PATH_TO_WORK, "confusion_matrices")

# Crear carpetas
for path in [PATH_TO_WORK, PATH_TO_TEMP_FILES, PATH_TO_OPTUNA_ARTIFACTS, PATH_TO_MODELS, PATH_TO_CMS]:
    os.makedirs(path, exist_ok=True)

# ======================
# OPTUNA (KAGGLE)
# ======================

OPTUNA_DB = f"{WORK_DIR}/optuna.db"

# ======================
# CONFIG
# ======================

MODEL_NAME = "ResNet50"
MODEL_VERSION = "1.0.0"

SEED = 42
BATCH_SIZE = 32
TEST_SIZE = 0.2
IMAGE_SIZE = 224
NUM_WORKERS = 2

class_names = ['0', '1', '2', '3', '4']
class_to_idx = {class_name: i for i, class_name in enumerate(class_names)}

# ======================
# SEED + DEVICE
# ======================

np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

Device: cuda

## 7. Lectura del CSV y verificación de imágenes

Se carga nuevamente el archivo `train.csv` usando la ruta definitiva del proyecto.  
Además, se verifica que las imágenes estén disponibles en el directorio esperado.

In [18]:
train_df = pd.read_csv(PATH_TO_TRAIN)

print("Shape train.csv:", train_df.shape)
display(train_df.head())

print("Cantidad de archivos en train_images:", len(os.listdir(PATH_TO_IMAGES_DIR)))
print("Primeros archivos:", os.listdir(PATH_TO_IMAGES_DIR)[:5])

print("\nDistribución AdoptionSpeed:")
display(
    (train_df["AdoptionSpeed"]
     .value_counts(normalize=True)
     .sort_index()
     .mul(100)
     .round(2)
     .to_frame("porcentaje"))
)

Shape train.csv: (14993, 24)

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,...,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,...,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,...,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,...,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,...,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

Cantidad de archivos en train_images: 58311
Primeros archivos: ['cf8d949f9-2.jpg', '61d4dc56b-12.jpg', '53923463d-9.jpg', '0173c456c-8.jpg', 'fa7c7d1be-3.jpg']

Distribución AdoptionSpeed:

               porcentaje
AdoptionSpeed
0                    2.73
1                   20.61
2                   26.93
3                   21.74
4                   27.99

## 8. Funciones de visualización

Se definen funciones auxiliares para inspeccionar imágenes del dataset.

In [20]:
def visualize_pet(pet_id):
    path_to_image = os.path.join(PATH_TO_IMAGES_DIR, f'{pet_id}-1.jpg')
    image_to_show = cv2.imread(path_to_image)
    if image_to_show is None:
        print(f"No se encontró imagen para PetID={pet_id}")
        return
    image_to_show = cv2.cvtColor(image_to_show, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(5, 5))
    plt.imshow(image_to_show)
    plt.axis('off')
    plt.show()

def visualize_image(image):
    image = cv2.convertScaleAbs(image)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    plt.figure(figsize=(5, 5))
    plt.imshow(image.astype(np.uint8))
    plt.axis('off')
    plt.show()

## 9. Split estratificado y organización de imágenes

Para entrenar el modelo con `ImageFolder`, las imágenes se copian a carpetas organizadas por clase.

Se realiza una división estratificada entre entrenamiento y validación para preservar la distribución de `AdoptionSpeed` en ambos subconjuntos.

In [21]:
CREATE_PYTORCH_DIRECTORIES = 1

new_train_directory = os.path.join(PATH_TO_WORK, "train_images_classes")
new_val_directory = os.path.join(PATH_TO_WORK, "val_images_classes")

os.makedirs(new_train_directory, exist_ok=True)
os.makedirs(new_val_directory, exist_ok=True)

for clase in class_names:
    os.makedirs(os.path.join(new_train_directory, clase), exist_ok=True)
    os.makedirs(os.path.join(new_val_directory, clase), exist_ok=True)

train_data, val_data = train_test_split(
    train_df,
    test_size=TEST_SIZE,
    random_state=SEED,
    stratify=train_df["AdoptionSpeed"]
)

train_data = train_data.copy()
val_data = val_data.copy()

print("Train:", train_data.shape)
print("Val:", val_data.shape)

print("\nDistribución train (%):")
print(
    train_data["AdoptionSpeed"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print("\nDistribución val (%):")
print(
    val_data["AdoptionSpeed"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

Train: (11994, 24)
Val: (2999, 24)

Distribución train (%):
AdoptionSpeed
0     2.73
1    20.61
2    26.93
3    21.74
4    27.99
Name: proportion, dtype: float64

Distribución val (%):
AdoptionSpeed
0     2.73
1    20.61
2    26.91
3    21.74
4    28.01
Name: proportion, dtype: float64

## 10. Copia de imágenes a carpetas por clase

Se copia la primera imagen disponible de cada mascota (`PetID-1.jpg`) al directorio correspondiente según su clase de `AdoptionSpeed`.

Este paso permite usar `datasets.ImageFolder`, que espera una estructura de carpetas donde cada subcarpeta representa una clase.

In [22]:
def copy_images_to_class_dirs(data, destination_dir):
    missing = 0
    copied = 0

    for _, row in tqdm(data.iterrows(), total=len(data)):
        pet_id = row["PetID"]
        adoption_speed = row["AdoptionSpeed"]

        file_name = f"{pet_id}-1.jpg"
        source = os.path.join(PATH_TO_IMAGES_DIR, file_name)
        target = os.path.join(destination_dir, str(adoption_speed), file_name)

        if os.path.exists(source):
            if not os.path.exists(target):
                shutil.copy2(source, target)
                copied += 1
        else:
            missing += 1

    print(f"Destino: {destination_dir}")
    print(f"Copiadas nuevas: {copied}")
    print(f"Faltantes: {missing}")

if CREATE_PYTORCH_DIRECTORIES == 1:
    copy_images_to_class_dirs(train_data, new_train_directory)
    copy_images_to_class_dirs(val_data, new_val_directory)
    print("Proceso de copia completado.")
else:
    print("Se omite copia de imágenes.")

100%|██████████| 11994/11994 [02:14<00:00, 89.29it/s]

Destino: /kaggle/working/train_images_classes
Copiadas nuevas: 11721
Faltantes: 273

100%|██████████| 2999/2999 [00:29<00:00, 101.88it/s]

Destino: /kaggle/working/val_images_classes
Copiadas nuevas: 2931
Faltantes: 68
Proceso de copia completado.

In [23]:
for clase in class_names:
    train_count = len(os.listdir(os.path.join(new_train_directory, clase)))
    val_count = len(os.listdir(os.path.join(new_val_directory, clase)))
    print(f"Clase {clase} | Train: {train_count} | Val: {val_count}")

Clase 0 | Train: 307 | Val: 79
Clase 1 | Train: 2445 | Val: 611
Clase 2 | Train: 3203 | Val: 798
Clase 3 | Train: 2584 | Val: 641
Clase 4 | Train: 3182 | Val: 802

Luego de la copia, se verifica que existan imágenes en cada carpeta de clase. Este control es necesario porque `ImageFolder` fallará si las carpetas están vacías.

## 11. Data augmentation y DataLoaders

Para entrenamiento se aplican transformaciones moderadas con el objetivo de mejorar la generalización del modelo.

Para validación no se utiliza data augmentation; solo se aplican transformaciones determinísticas.

In [24]:
def create_dataloaders(train_directory, val_directory, batch_size, num_workers):
    train_transforms = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.RandomResizedCrop(IMAGE_SIZE, scale=(0.8, 1.0)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.RandomRotation(10),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    val_transforms = transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.CenterCrop(IMAGE_SIZE),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
        )
    ])

    train_dataset = datasets.ImageFolder(train_directory, transform=train_transforms)
    val_dataset = datasets.ImageFolder(val_directory, transform=val_transforms)

    train_dataset.class_to_idx = class_to_idx
    val_dataset.class_to_idx = class_to_idx

    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available()
    )

    val_loader = torch.utils.data.DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available()
    )

    return train_dataset, val_dataset, train_loader, val_loader

train_dataset, val_dataset, train_dataloader, val_dataloader = create_dataloaders(
    new_train_directory,
    new_val_directory,
    BATCH_SIZE,
    NUM_WORKERS
)

print("Train images cargadas:", len(train_dataset))
print("Val images cargadas:", len(val_dataset))
print("Clases:", train_dataset.classes)

Train images cargadas: 11721
Val images cargadas: 2931
Clases: ['0', '1', '2', '3', '4']

Las clases son detectadas automáticamente por `ImageFolder` a partir del nombre de las carpetas. En este caso, las clases corresponden a los valores de `AdoptionSpeed`.

## 12. Función para matriz de confusión

Se define una función auxiliar para visualizar matrices de confusión.  
Esta matriz permite identificar qué clases son confundidas con mayor frecuencia por el modelo.

In [25]:
def plot_confusion_matrix(y_true, y_pred, classes=None, normalize=False, title="Matriz de confusión"):
    cm = confusion_matrix(y_true, y_pred)

    if normalize:
        cm = cm.astype("float") / cm.sum(axis=1, keepdims=True)
        cm = np.nan_to_num(cm)

    if classes is None:
        classes = [str(i) for i in range(cm.shape[0])]

    fig, ax = plt.subplots(figsize=(7, 7))
    im = ax.imshow(cm)
    fig.colorbar(im, ax=ax)

    ax.set(
        xticks=np.arange(len(classes)),
        yticks=np.arange(len(classes)),
        xticklabels=classes,
        yticklabels=classes,
        ylabel="True label",
        xlabel="Predicted label",
        title=title
    )

    plt.setp(ax.get_xticklabels(), rotation=45, ha="right")

    thresh = cm.max() / 2 if cm.max() > 0 else 0
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            value = f"{cm[i, j]:.2f}" if normalize else f"{int(cm[i, j])}"
            ax.text(
                j, i, value,
                ha="center",
                va="center",
                color="white" if cm[i, j] > thresh else "black"
            )

    fig.tight_layout()
    return fig

## 13. Función de entrenamiento y validación

La función `train_val` entrena el modelo y evalúa su desempeño en validación en cada epoch.

Para cada fase calcula:
- loss;
- accuracy;
- Quadratic Weighted Kappa.

El mejor modelo se selecciona según el valor de QWK en validación.

In [26]:
def train_val(
    model,
    criterion,
    dataloaders,
    datasets,
    device,
    num_epochs=5,
    lr=0.001,
    momentum=0.9,
    experiment_name="experiment"
):
    optimizer = optim.SGD(
        filter(lambda p: p.requires_grad, model.parameters()),
        lr=lr,
        momentum=momentum
    )

    since = time.time()

    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0
    best_kappa = -999
    best_cm_path = None

    history = []

    for epoch in range(num_epochs):
        print(f"Epoch {epoch}/{num_epochs - 1}")
        print("-" * 10)

        for phase in ["train", "val"]:
            if phase == "train":
                model.train()
            else:
                model.eval()

            running_loss = 0.0
            running_corrects = 0

            y_true_epoch = []
            y_pred_epoch = []

            for inputs, labels in tqdm(dataloaders[phase]):
                inputs = inputs.to(device)
                labels = labels.to(device)

                optimizer.zero_grad()

                with torch.set_grad_enabled(phase == "train"):
                    outputs = model(inputs)
                    _, preds = torch.max(outputs, 1)
                    loss = criterion(outputs, labels)

                    if phase == "train":
                        loss.backward()
                        optimizer.step()

                running_loss += loss.item() * inputs.size(0)
                running_corrects += torch.sum(preds == labels.data)

                if phase == "val":
                    y_true_epoch.extend(labels.detach().cpu().numpy().tolist())
                    y_pred_epoch.extend(preds.detach().cpu().numpy().tolist())

            epoch_loss = running_loss / len(datasets[phase])
            epoch_acc = running_corrects.double().item() / len(datasets[phase])

            if phase == "val":
                epoch_kappa = cohen_kappa_score(
                    y_true_epoch,
                    y_pred_epoch,
                    weights="quadratic"
                )
            else:
                epoch_kappa = np.nan

            print(
                f"{phase.title()} Loss: {epoch_loss:.4f} "
                f"Acc: {epoch_acc * 100:.2f}% "
                f"Kappa: {epoch_kappa if not np.isnan(epoch_kappa) else np.nan:.3f}"
            )

            history.append({
                "experiment": experiment_name,
                "epoch": epoch,
                "phase": phase,
                "loss": epoch_loss,
                "accuracy": epoch_acc,
                "kappa": epoch_kappa
            })

            if phase == "val" and epoch_kappa > best_kappa:
                best_acc = epoch_acc
                best_kappa = epoch_kappa
                best_model_wts = copy.deepcopy(model.state_dict())

                cm_filename = f"{experiment_name}_epoch_{epoch}_kappa_{epoch_kappa:.3f}.jpg"
                cm_path = os.path.join(PATH_TO_CMS, cm_filename)

                fig = plot_confusion_matrix(
                    y_true_epoch,
                    y_pred_epoch,
                    classes=class_names,
                    normalize=False,
                    title=f"{experiment_name} - CM epoch {epoch}"
                )
                fig.savefig(cm_path, dpi=150, bbox_inches="tight")
                plt.close(fig)
                best_cm_path = cm_path

        print()

    time_elapsed = time.time() - since
    print(f"Training complete in {time_elapsed // 60:.0f}m {time_elapsed % 60:.0f}s")
    print(f"Best val Acc: {best_acc * 100:.2f}%")
    print(f"Best val Kappa: {best_kappa:.3f}")
    if best_cm_path:
        print(f"Best confusion matrix saved at: {best_cm_path}")

    model.load_state_dict(best_model_wts)

    run_id = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    model_path = os.path.join(PATH_TO_MODELS, f"{experiment_name}_{run_id}.pth")
    torch.save(model.state_dict(), model_path)
    print(f"Modelo guardado en: {model_path}")

    return model, best_kappa, pd.DataFrame(history), model_path, best_cm_path

## 14. Construcción del modelo ResNet50

Se utiliza ResNet50 preentrenada y se reemplaza la capa final para adaptar la salida a cinco clases.

Según el experimento, se entrenan:
- solo la capa fully connected final;
- la capa final + `layer4`.

Esto permite comparar una estrategia de extracción de características frente a una estrategia de fine-tuning.

In [27]:
def build_resnet50_model(
    num_classes=5,
    unfreeze_layer4=False,
    unfreeze_layer3=False
):
    model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)

    for param in model.parameters():
        param.requires_grad = False

    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, num_classes)

    if unfreeze_layer4:
        for param in model.layer4.parameters():
            param.requires_grad = True

    if unfreeze_layer3:
        for param in model.layer3.parameters():
            param.requires_grad = True

    model = model.to(device)
    return model


def count_trainable_params(model):
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    return trainable, total

## 15. Guardado de resultados

Se define una función auxiliar para guardar modelos, matrices de confusión e historiales de entrenamiento.

In [28]:
SAVE_DIR = "/kaggle/working/experimentos"

os.makedirs(SAVE_DIR, exist_ok=True)
os.makedirs(f"{SAVE_DIR}/models", exist_ok=True)
os.makedirs(f"{SAVE_DIR}/confusion_matrices", exist_ok=True)
os.makedirs(f"{SAVE_DIR}/histories", exist_ok=True)
os.makedirs(f"{SAVE_DIR}/studies", exist_ok=True)

def save_experiment_outputs(exp_name, model_path, cm_path, history=None, study=None):
    if model_path is not None and os.path.exists(model_path):
        shutil.copy(model_path, f"{SAVE_DIR}/models/{exp_name}_best_model.pth")

    if cm_path is not None and os.path.exists(cm_path):
        shutil.copy(cm_path, f"{SAVE_DIR}/confusion_matrices/{exp_name}_confusion_matrix.jpg")

    if history is not None:
        joblib.dump(history, f"{SAVE_DIR}/histories/{exp_name}_history.pkl")

    if study is not None:
        joblib.dump(study, f"{SAVE_DIR}/studies/{exp_name}_study.pkl")

    pd.DataFrame(results).to_csv(f"{SAVE_DIR}/results_summary.csv", index=False)

    print(f"Guardado completo en: {SAVE_DIR}")

## 16. Inicialización de contenedores de resultados

Se inicializan listas para guardar los resultados resumidos y los historiales de entrenamiento de todos los experimentos.

In [ ]:
results = []
all_histories = []

# Experimentos

A partir de la arquitectura ResNet50 preentrenada, se diseñaron distintos experimentos para evaluar el impacto de tres decisiones principales:

1. entrenar solo la capa final fully connected o realizar fine-tuning de `layer4`;
2. modificar el tamaño de batch;
3. optimizar hiperparámetros mediante Optuna.

En todos los casos, el desempeño se evalúa sobre el conjunto de validación mediante Quadratic Weighted Kappa (QWK).

### Experimento 1 — Optimización de la capa final fully connected

En este primer experimento se entrena únicamente la capa final del modelo (`fc`), manteniendo congeladas las capas convolucionales de ResNet50.

Este experimento funciona como línea base, ya que permite evaluar cuánto desempeño se obtiene utilizando la red preentrenada como extractor fijo de características.

In [27]:
EXP_NAME = "exp1_optuna_fc_only"

def optuna_train_exp1(trial):
    print(f"\nTRIAL {trial.number}")

    lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
    momentum = trial.suggest_float("momentum", 0.80, 0.95)
    epochs = trial.suggest_int("epochs", 4, 6)

    model = build_resnet50_model(
        num_classes=5,
        unfreeze_layer4=False,
        unfreeze_layer3=False
    )

    criterion = nn.CrossEntropyLoss()

    model, kappa, history, model_path, cm_path = train_val(
        model,
        criterion,
        {"train": train_dataloader, "val": val_dataloader},
        {"train": train_dataset, "val": val_dataset},
        device,
        epochs,
        lr,
        momentum,
        f"{EXP_NAME}_trial_{trial.number}"
    )

    results.append({
        "experiment": EXP_NAME,
        "trial": trial.number,
        "batch_size": BATCH_SIZE,
        "unfreeze_layer4": False,
        "unfreeze_layer3": False,
        "lr": lr,
        "momentum": momentum,
        "epochs": epochs,
        "kappa": kappa,
        "model_path": model_path,
        "cm_path": cm_path
    })

    all_histories.append(history)

    trial.set_user_attr("model_path", model_path)
    trial.set_user_attr("cm_path", cm_path)

    return kappa


study_exp1 = optuna.create_study(
    direction="maximize",
    study_name=EXP_NAME,
    storage=f"sqlite:///{OPTUNA_DB}",
    load_if_exists=True
)

study_exp1.optimize(optuna_train_exp1, n_trials=20)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)
shutil.copy(OPTUNA_DB, f"/kaggle/working/{EXP_NAME}_optuna_backup.db")

print("Experimento 1 finalizado y respaldado.")

[I 2026-04-29 11:50:50,662] Using an existing study with name 'exp1_optuna_fc_only' instead of creating a new one.

TRIAL 1
Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 187MB/s]

Epoch 0/4
----------

100%|██████████| 367/367 [00:43<00:00,  8.46it/s]

Train Loss: 1.5207 Acc: 28.07% Kappa: nan

100%|██████████| 92/92 [00:09<00:00, 10.07it/s]

Val Loss: 1.4694 Acc: 30.19% Kappa: 0.112

Epoch 1/4
----------

100%|██████████| 367/367 [00:44<00:00,  8.22it/s]

Train Loss: 1.4573 Acc: 31.99% Kappa: nan

100%|██████████| 92/92 [00:11<00:00,  8.07it/s]

Val Loss: 1.4436 Acc: 31.83% Kappa: 0.187

Epoch 2/4
----------

100%|██████████| 367/367 [00:44<00:00,  8.17it/s]

Train Loss: 1.4385 Acc: 33.28% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.91it/s]

Val Loss: 1.4330 Acc: 33.33% Kappa: 0.236

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.03it/s]

Train Loss: 1.4277 Acc: 34.06% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.84it/s]

Val Loss: 1.4254 Acc: 33.37% Kappa: 0.242

Epoch 4/4
----------

100%|██████████| 367/367 [00:44<00:00,  8.16it/s]

Train Loss: 1.4212 Acc: 34.72% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4190 Acc: 33.85% Kappa: 0.258

[I 2026-04-29 11:55:29,248] Trial 1 finished with value: 0.2581863448307462 and parameters: {'lr': 0.0001389063180681716, 'momentum': 0.8780673694483, 'epochs': 5}. Best is trial 1 with value: 0.2581863448307462.

Training complete in 4m 37s
Best val Acc: 33.85%
Best val Kappa: 0.258
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_1_epoch_4_kappa_0.258.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_1_20260429_115529.pth

TRIAL 2
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.13it/s]

Train Loss: 1.5405 Acc: 26.28% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.78it/s]

Val Loss: 1.5010 Acc: 29.21% Kappa: 0.077

Epoch 1/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.10it/s]

Train Loss: 1.4778 Acc: 30.09% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.71it/s]

Val Loss: 1.4663 Acc: 30.57% Kappa: 0.137

Epoch 2/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.4560 Acc: 32.22% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]

Val Loss: 1.4516 Acc: 32.34% Kappa: 0.184

Epoch 3/3
----------

100%|██████████| 367/367 [00:46<00:00,  7.96it/s]

Train Loss: 1.4447 Acc: 33.11% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.75it/s]

Val Loss: 1.4439 Acc: 32.65% Kappa: 0.215

[I 2026-04-29 11:59:15,352] Trial 2 finished with value: 0.21549790738653896 and parameters: {'lr': 0.00011192131786486305, 'momentum': 0.8242865391880786, 'epochs': 4}. Best is trial 1 with value: 0.2581863448307462.

Training complete in 3m 45s
Best val Acc: 32.65%
Best val Kappa: 0.215
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_2_epoch_3_kappa_0.215.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_2_20260429_115915.pth

TRIAL 3
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.04it/s]

Train Loss: 1.4364 Acc: 32.69% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4078 Acc: 35.04% Kappa: 0.256

Epoch 1/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.04it/s]

Train Loss: 1.3945 Acc: 36.61% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.4038 Acc: 34.80% Kappa: 0.267

Epoch 2/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.04it/s]

Train Loss: 1.3757 Acc: 37.80% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4044 Acc: 35.86% Kappa: 0.265

Epoch 3/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.05it/s]

Train Loss: 1.3694 Acc: 38.24% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.68it/s]

Val Loss: 1.4064 Acc: 34.36% Kappa: 0.284

[I 2026-04-29 12:03:01,766] Trial 3 finished with value: 0.2844562454383007 and parameters: {'lr': 0.00104429383808488, 'momentum': 0.9322098069296705, 'epochs': 4}. Best is trial 3 with value: 0.2844562454383007.

Training complete in 3m 46s
Best val Acc: 34.36%
Best val Kappa: 0.284
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_3_epoch_3_kappa_0.284.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_3_20260429_120301.pth

TRIAL 4
Epoch 0/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.03it/s]

Train Loss: 1.4785 Acc: 30.48% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4353 Acc: 33.06% Kappa: 0.223

Epoch 1/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.01it/s]

Train Loss: 1.4281 Acc: 33.67% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.4185 Acc: 34.25% Kappa: 0.248

Epoch 2/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.06it/s]

Train Loss: 1.4152 Acc: 35.01% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]

Val Loss: 1.4114 Acc: 35.07% Kappa: 0.261

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.10it/s]

Train Loss: 1.4047 Acc: 36.26% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.79it/s]

Val Loss: 1.4082 Acc: 34.80% Kappa: 0.270

Epoch 4/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.3994 Acc: 35.90% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.68it/s]

Val Loss: 1.4052 Acc: 35.18% Kappa: 0.274

[I 2026-04-29 12:07:44,312] Trial 4 finished with value: 0.27436936629406883 and parameters: {'lr': 0.0004307177148637245, 'momentum': 0.8373878989486954, 'epochs': 5}. Best is trial 3 with value: 0.2844562454383007.

Training complete in 4m 42s
Best val Acc: 35.18%
Best val Kappa: 0.274
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_4_epoch_4_kappa_0.274.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_4_20260429_120744.pth

TRIAL 5
Epoch 0/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.03it/s]

Train Loss: 1.5379 Acc: 26.71% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.72it/s]

Val Loss: 1.4936 Acc: 30.19% Kappa: 0.114

Epoch 1/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.06it/s]

Train Loss: 1.4749 Acc: 31.24% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.69it/s]

Val Loss: 1.4627 Acc: 31.97% Kappa: 0.159

Epoch 2/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.4522 Acc: 32.86% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4477 Acc: 32.51% Kappa: 0.184

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.10it/s]

Train Loss: 1.4408 Acc: 33.60% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.81it/s]

Val Loss: 1.4383 Acc: 33.20% Kappa: 0.208

Epoch 4/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.05it/s]

Train Loss: 1.4321 Acc: 34.16% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]

Val Loss: 1.4322 Acc: 33.78% Kappa: 0.221

[I 2026-04-29 12:12:26,417] Trial 5 finished with value: 0.22129257444509953 and parameters: {'lr': 0.00010260557263538911, 'momentum': 0.8586725379473524, 'epochs': 5}. Best is trial 3 with value: 0.2844562454383007.

Training complete in 4m 41s
Best val Acc: 33.78%
Best val Kappa: 0.221
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_5_epoch_4_kappa_0.221.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_5_20260429_121226.pth

TRIAL 6
Epoch 0/4
----------

100%|██████████| 367/367 [00:46<00:00,  7.96it/s]

Train Loss: 1.4804 Acc: 29.85% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.74it/s]

Val Loss: 1.4364 Acc: 33.71% Kappa: 0.206

Epoch 1/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.4282 Acc: 34.01% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.69it/s]

Val Loss: 1.4205 Acc: 34.19% Kappa: 0.242

Epoch 2/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.02it/s]

Train Loss: 1.4123 Acc: 35.27% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.80it/s]

Val Loss: 1.4126 Acc: 34.32% Kappa: 0.253

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.4065 Acc: 35.55% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.72it/s]

Val Loss: 1.4084 Acc: 34.53% Kappa: 0.257

Epoch 4/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.02it/s]

Train Loss: 1.3992 Acc: 36.37% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.4057 Acc: 34.87% Kappa: 0.265

Training complete in 4m 42s
Best val Acc: 34.87%
Best val Kappa: 0.265
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_6_epoch_4_kappa_0.265.jpg

[I 2026-04-29 12:17:09,511] Trial 6 finished with value: 0.2651765198320478 and parameters: {'lr': 0.0005505598075459087, 'momentum': 0.8074495096379066, 'epochs': 5}. Best is trial 3 with value: 0.2844562454383007.

Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_6_20260429_121709.pth

TRIAL 7
Epoch 0/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.04it/s]

Train Loss: 1.4335 Acc: 33.61% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4256 Acc: 34.02% Kappa: 0.263

Epoch 1/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.04it/s]

Train Loss: 1.3876 Acc: 36.82% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.74it/s]

Val Loss: 1.4539 Acc: 34.46% Kappa: 0.220

Epoch 2/5
----------

100%|██████████| 367/367 [00:44<00:00,  8.18it/s]

Train Loss: 1.3726 Acc: 38.41% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.4517 Acc: 34.53% Kappa: 0.247

Epoch 3/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.12it/s]

Train Loss: 1.3614 Acc: 39.03% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.60it/s]

Val Loss: 1.4626 Acc: 33.44% Kappa: 0.231

Epoch 4/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.15it/s]

Train Loss: 1.3528 Acc: 40.14% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.73it/s]

Val Loss: 1.4735 Acc: 33.13% Kappa: 0.224

Epoch 5/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.04it/s]

Train Loss: 1.3379 Acc: 40.47% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.85it/s]

Val Loss: 1.4652 Acc: 32.89% Kappa: 0.242

Training complete in 5m 36s
Best val Acc: 34.02%
Best val Kappa: 0.263
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_7_epoch_0_kappa_0.263.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_7_20260429_122245.pth

[I 2026-04-29 12:22:46,020] Trial 7 finished with value: 0.2625934074824551 and parameters: {'lr': 0.003884247878999172, 'momentum': 0.9447544670714936, 'epochs': 6}. Best is trial 3 with value: 0.2844562454383007.

TRIAL 8
Epoch 0/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.08it/s]

Train Loss: 1.4304 Acc: 33.61% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.55it/s]

Val Loss: 1.4435 Acc: 34.53% Kappa: 0.223

Epoch 1/5
----------

100%|██████████| 367/367 [00:44<00:00,  8.27it/s]

Train Loss: 1.3858 Acc: 37.44% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.64it/s]

Val Loss: 1.4303 Acc: 34.90% Kappa: 0.258

Epoch 2/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.3639 Acc: 39.15% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.78it/s]

Val Loss: 1.4301 Acc: 34.39% Kappa: 0.270

Epoch 3/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.13it/s]

Train Loss: 1.3572 Acc: 39.19% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.81it/s]

Val Loss: 1.4291 Acc: 36.06% Kappa: 0.273

Epoch 4/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.3438 Acc: 40.33% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.76it/s]

Val Loss: 1.4415 Acc: 34.08% Kappa: 0.262

Epoch 5/5
----------

100%|██████████| 367/367 [00:44<00:00,  8.23it/s]

Train Loss: 1.3368 Acc: 41.19% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.60it/s]
[I 2026-04-29 12:28:21,397] Trial 8 finished with value: 0.27290585877649054 and parameters: {'lr': 0.005615561107158513, 'momentum': 0.9026294480604613, 'epochs': 6}. Best is trial 3 with value: 0.2844562454383007.

Val Loss: 1.4528 Acc: 33.16% Kappa: 0.230

Training complete in 5m 35s
Best val Acc: 36.06%
Best val Kappa: 0.273
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_8_epoch_3_kappa_0.273.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_8_20260429_122821.pth

TRIAL 9
Epoch 0/5
----------

100%|██████████| 367/367 [00:44<00:00,  8.16it/s]

Train Loss: 1.4317 Acc: 33.60% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.79it/s]

Val Loss: 1.4233 Acc: 34.22% Kappa: 0.229

Epoch 1/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.10it/s]

Train Loss: 1.3805 Acc: 37.51% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.80it/s]

Val Loss: 1.4149 Acc: 35.45% Kappa: 0.247

Epoch 2/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.13it/s]

Train Loss: 1.3682 Acc: 38.85% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4359 Acc: 34.70% Kappa: 0.245

Epoch 3/5
----------

100%|██████████| 367/367 [00:44<00:00,  8.21it/s]

Train Loss: 1.3557 Acc: 39.52% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.71it/s]

Val Loss: 1.4346 Acc: 34.77% Kappa: 0.257

Epoch 4/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.3458 Acc: 40.20% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.82it/s]

Val Loss: 1.4367 Acc: 33.71% Kappa: 0.255

Epoch 5/5
----------

100%|██████████| 367/367 [00:44<00:00,  8.18it/s]

Train Loss: 1.3343 Acc: 40.66% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.64it/s]
[I 2026-04-29 12:33:56,460] Trial 9 finished with value: 0.2573591759121281 and parameters: {'lr': 0.0043099963345244255, 'momentum': 0.9113320706610045, 'epochs': 6}. Best is trial 3 with value: 0.2844562454383007.

Val Loss: 1.4420 Acc: 34.53% Kappa: 0.248

Training complete in 5m 34s
Best val Acc: 34.77%
Best val Kappa: 0.257
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_9_epoch_3_kappa_0.257.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_9_20260429_123356.pth

TRIAL 10
Epoch 0/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.06it/s]

Train Loss: 1.4266 Acc: 33.29% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.75it/s]

Val Loss: 1.4020 Acc: 35.86% Kappa: 0.289

Epoch 1/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.3888 Acc: 36.45% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.62it/s]

Val Loss: 1.4071 Acc: 35.65% Kappa: 0.268

Epoch 2/4
----------

100%|██████████| 367/367 [00:44<00:00,  8.16it/s]

Train Loss: 1.3782 Acc: 36.86% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.75it/s]

Val Loss: 1.4060 Acc: 34.66% Kappa: 0.280

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.15it/s]

Train Loss: 1.3639 Acc: 38.89% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.61it/s]

Val Loss: 1.4090 Acc: 35.18% Kappa: 0.287

Epoch 4/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.3538 Acc: 39.47% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.78it/s]

Val Loss: 1.4121 Acc: 35.28% Kappa: 0.279

Training complete in 4m 39s
Best val Acc: 35.86%
Best val Kappa: 0.289
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_10_epoch_0_kappa_0.289.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_10_20260429_123836.pth

[I 2026-04-29 12:38:36,306] Trial 10 finished with value: 0.28885548609205836 and parameters: {'lr': 0.0033149247816342685, 'momentum': 0.8613940384224743, 'epochs': 5}. Best is trial 10 with value: 0.28885548609205836.

TRIAL 11
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.15it/s]

Train Loss: 1.4367 Acc: 33.17% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.75it/s]

Val Loss: 1.4072 Acc: 34.60% Kappa: 0.279

Epoch 1/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.15it/s]

Train Loss: 1.3973 Acc: 36.62% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.71it/s]

Val Loss: 1.3997 Acc: 35.07% Kappa: 0.271

Epoch 2/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.3826 Acc: 36.86% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.79it/s]

Val Loss: 1.3998 Acc: 35.28% Kappa: 0.279

Epoch 3/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.3713 Acc: 38.93% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.60it/s]
[I 2026-04-29 12:42:20,084] Trial 11 finished with value: 0.2791613833608052 and parameters: {'lr': 0.0017280930986178355, 'momentum': 0.8704448670433707, 'epochs': 4}. Best is trial 10 with value: 0.28885548609205836.

Val Loss: 1.4009 Acc: 35.18% Kappa: 0.279

Training complete in 3m 43s
Best val Acc: 34.60%
Best val Kappa: 0.279
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_11_epoch_0_kappa_0.279.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_11_20260429_124219.pth

TRIAL 12
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.4312 Acc: 33.50% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.80it/s]

Val Loss: 1.4066 Acc: 34.36% Kappa: 0.264

Epoch 1/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.02it/s]

Train Loss: 1.3869 Acc: 36.75% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.71it/s]

Val Loss: 1.4013 Acc: 35.24% Kappa: 0.275

Epoch 2/3
----------

100%|██████████| 367/367 [00:44<00:00,  8.22it/s]

Train Loss: 1.3704 Acc: 37.86% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.58it/s]

Val Loss: 1.4137 Acc: 35.04% Kappa: 0.264

Epoch 3/3
----------

100%|██████████| 367/367 [00:44<00:00,  8.17it/s]

Train Loss: 1.3591 Acc: 39.18% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.82it/s]

Val Loss: 1.4097 Acc: 35.21% Kappa: 0.282

[I 2026-04-29 12:46:04,387] Trial 12 finished with value: 0.2817513232352772 and parameters: {'lr': 0.001519973461177926, 'momentum': 0.9431301761690051, 'epochs': 4}. Best is trial 10 with value: 0.28885548609205836.

Training complete in 3m 44s
Best val Acc: 35.21%
Best val Kappa: 0.282
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_12_epoch_3_kappa_0.282.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_12_20260429_124604.pth

TRIAL 13
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.12it/s]

Train Loss: 1.4305 Acc: 33.15% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.77it/s]

Val Loss: 1.4110 Acc: 34.19% Kappa: 0.269

Epoch 1/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.3878 Acc: 36.81% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.60it/s]

Val Loss: 1.4115 Acc: 36.13% Kappa: 0.273

Epoch 2/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.15it/s]

Train Loss: 1.3728 Acc: 37.36% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.75it/s]

Val Loss: 1.4135 Acc: 35.14% Kappa: 0.297

Epoch 3/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.3617 Acc: 38.71% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.72it/s]
[I 2026-04-29 12:49:48,522] Trial 13 finished with value: 0.2965774006415449 and parameters: {'lr': 0.002198906159202721, 'momentum': 0.9079534063660759, 'epochs': 4}. Best is trial 13 with value: 0.2965774006415449.

Val Loss: 1.4169 Acc: 34.60% Kappa: 0.257

Training complete in 3m 43s
Best val Acc: 35.14%
Best val Kappa: 0.297
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_13_epoch_2_kappa_0.297.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_13_20260429_124948.pth

TRIAL 14
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.4394 Acc: 32.74% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.79it/s]

Val Loss: 1.4288 Acc: 35.24% Kappa: 0.248

Epoch 1/3
----------

100%|██████████| 367/367 [00:44<00:00,  8.18it/s]

Train Loss: 1.3946 Acc: 36.78% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.61it/s]

Val Loss: 1.4408 Acc: 34.77% Kappa: 0.264

Epoch 2/3
----------

100%|██████████| 367/367 [00:44<00:00,  8.18it/s]

Train Loss: 1.3726 Acc: 37.67% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.83it/s]

Val Loss: 1.4836 Acc: 33.98% Kappa: 0.217

Epoch 3/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.3574 Acc: 39.03% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]
[I 2026-04-29 12:53:32,195] Trial 14 finished with value: 0.26384982372172316 and parameters: {'lr': 0.008638101720511743, 'momentum': 0.8921798636004764, 'epochs': 4}. Best is trial 13 with value: 0.2965774006415449.

Val Loss: 1.4665 Acc: 33.78% Kappa: 0.228

Training complete in 3m 43s
Best val Acc: 34.77%
Best val Kappa: 0.264
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_14_epoch_1_kappa_0.264.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_14_20260429_125332.pth

TRIAL 15
Epoch 0/4
----------

100%|██████████| 367/367 [00:44<00:00,  8.19it/s]

Train Loss: 1.4330 Acc: 33.54% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4059 Acc: 35.24% Kappa: 0.283

Epoch 1/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.07it/s]

Train Loss: 1.3936 Acc: 35.99% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.69it/s]

Val Loss: 1.4047 Acc: 35.04% Kappa: 0.265

Epoch 2/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.3780 Acc: 38.20% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.72it/s]

Val Loss: 1.4033 Acc: 35.07% Kappa: 0.278

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.08it/s]

Train Loss: 1.3693 Acc: 38.60% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.78it/s]

Val Loss: 1.4051 Acc: 35.21% Kappa: 0.292

Epoch 4/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.12it/s]

Train Loss: 1.3590 Acc: 39.44% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]
[I 2026-04-29 12:58:12,392] Trial 15 finished with value: 0.29228063076118227 and parameters: {'lr': 0.0025145292397229903, 'momentum': 0.852524885064331, 'epochs': 5}. Best is trial 13 with value: 0.2965774006415449.

Val Loss: 1.4107 Acc: 35.99% Kappa: 0.292

Training complete in 4m 40s
Best val Acc: 35.21%
Best val Kappa: 0.292
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_15_epoch_3_kappa_0.292.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_15_20260429_125812.pth

TRIAL 16
Epoch 0/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.4350 Acc: 33.44% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.68it/s]

Val Loss: 1.4083 Acc: 35.79% Kappa: 0.276

Epoch 1/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.3966 Acc: 36.58% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4055 Acc: 35.48% Kappa: 0.263

Epoch 2/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.06it/s]

Train Loss: 1.3824 Acc: 37.79% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.80it/s]

Val Loss: 1.4071 Acc: 34.70% Kappa: 0.281

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.13it/s]

Train Loss: 1.3737 Acc: 38.40% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.4039 Acc: 35.72% Kappa: 0.281

Epoch 4/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.3657 Acc: 38.55% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.71it/s]
[I 2026-04-29 13:02:53,672] Trial 16 finished with value: 0.2812045631905369 and parameters: {'lr': 0.0020685136906444133, 'momentum': 0.8416488987809959, 'epochs': 5}. Best is trial 13 with value: 0.2965774006415449.

Val Loss: 1.4045 Acc: 34.97% Kappa: 0.269

Training complete in 4m 40s
Best val Acc: 35.72%
Best val Kappa: 0.281
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_16_epoch_3_kappa_0.281.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_16_20260429_130253.pth

TRIAL 17
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.10it/s]

Train Loss: 1.4489 Acc: 32.37% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]

Val Loss: 1.4180 Acc: 34.22% Kappa: 0.227

Epoch 1/3
----------

100%|██████████| 367/367 [00:44<00:00,  8.16it/s]

Train Loss: 1.4062 Acc: 35.89% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.78it/s]

Val Loss: 1.4095 Acc: 34.15% Kappa: 0.259

Epoch 2/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.00it/s]

Train Loss: 1.3923 Acc: 36.61% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.73it/s]

Val Loss: 1.4047 Acc: 34.70% Kappa: 0.273

Epoch 3/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.10it/s]

Train Loss: 1.3851 Acc: 37.31% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.60it/s]

Val Loss: 1.4017 Acc: 35.11% Kappa: 0.278

[I 2026-04-29 13:06:39,192] Trial 17 finished with value: 0.2776031004966386 and parameters: {'lr': 0.000578994636350639, 'momentum': 0.9193403228538573, 'epochs': 4}. Best is trial 13 with value: 0.2965774006415449.

Training complete in 3m 45s
Best val Acc: 35.11%
Best val Kappa: 0.278
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_17_epoch_3_kappa_0.278.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_17_20260429_130639.pth

TRIAL 18
Epoch 0/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.03it/s]

Train Loss: 1.4310 Acc: 33.35% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.80it/s]

Val Loss: 1.4076 Acc: 34.94% Kappa: 0.239

Epoch 1/5
----------

100%|██████████| 367/367 [00:44<00:00,  8.17it/s]

Train Loss: 1.3894 Acc: 36.45% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.56it/s]

Val Loss: 1.4039 Acc: 35.04% Kappa: 0.275

Epoch 2/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.3758 Acc: 38.27% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.83it/s]

Val Loss: 1.4067 Acc: 34.32% Kappa: 0.276

Epoch 3/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.3607 Acc: 39.58% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.69it/s]

Val Loss: 1.4113 Acc: 34.63% Kappa: 0.269

Epoch 4/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.15it/s]

Train Loss: 1.3532 Acc: 39.62% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.61it/s]

Val Loss: 1.4202 Acc: 34.90% Kappa: 0.260

Epoch 5/5
----------

100%|██████████| 367/367 [00:45<00:00,  8.09it/s]

Train Loss: 1.3453 Acc: 40.24% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.78it/s]

Val Loss: 1.4126 Acc: 34.94% Kappa: 0.280

[I 2026-04-29 13:12:15,503] Trial 18 finished with value: 0.27953909054652215 and parameters: {'lr': 0.002776991946860137, 'momentum': 0.8875906193569449, 'epochs': 6}. Best is trial 13 with value: 0.2965774006415449.

Training complete in 5m 36s
Best val Acc: 34.94%
Best val Kappa: 0.280
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_18_epoch_5_kappa_0.280.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_18_20260429_131215.pth

TRIAL 19
Epoch 0/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.4503 Acc: 32.34% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4191 Acc: 34.25% Kappa: 0.236

Epoch 1/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.4063 Acc: 35.93% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.79it/s]

Val Loss: 1.4083 Acc: 34.73% Kappa: 0.273

Epoch 2/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.08it/s]

Train Loss: 1.3942 Acc: 36.56% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.68it/s]

Val Loss: 1.4031 Acc: 35.79% Kappa: 0.274

Epoch 3/3
----------

100%|██████████| 367/367 [00:45<00:00,  8.13it/s]

Train Loss: 1.3855 Acc: 36.98% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.60it/s]

Val Loss: 1.4020 Acc: 35.14% Kappa: 0.280

[I 2026-04-29 13:16:00,557] Trial 19 finished with value: 0.279704536265139 and parameters: {'lr': 0.0010855950225201365, 'momentum': 0.8491731604683463, 'epochs': 4}. Best is trial 13 with value: 0.2965774006415449.

Training complete in 3m 44s
Best val Acc: 35.14%
Best val Kappa: 0.280
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_19_epoch_3_kappa_0.280.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_19_20260429_131600.pth

TRIAL 20
Epoch 0/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.06it/s]

Train Loss: 1.4260 Acc: 33.39% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.84it/s]

Val Loss: 1.4086 Acc: 35.35% Kappa: 0.280

Epoch 1/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.11it/s]

Train Loss: 1.3876 Acc: 37.19% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.64it/s]

Val Loss: 1.4138 Acc: 35.28% Kappa: 0.283

Epoch 2/4
----------

100%|██████████| 367/367 [00:44<00:00,  8.21it/s]

Train Loss: 1.3722 Acc: 37.41% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.60it/s]

Val Loss: 1.4215 Acc: 34.36% Kappa: 0.267

Epoch 3/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.12it/s]

Train Loss: 1.3536 Acc: 39.66% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.79it/s]

Val Loss: 1.4355 Acc: 34.49% Kappa: 0.265

Epoch 4/4
----------

100%|██████████| 367/367 [00:45<00:00,  8.14it/s]

Train Loss: 1.3477 Acc: 39.39% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.59it/s]
[I 2026-04-29 13:20:40,480] Trial 20 finished with value: 0.2827752606647319 and parameters: {'lr': 0.00956319538241362, 'momentum': 0.8048399004601832, 'epochs': 5}. Best is trial 13 with value: 0.2965774006415449.

Val Loss: 1.4486 Acc: 31.18% Kappa: 0.217

Training complete in 4m 39s
Best val Acc: 35.28%
Best val Kappa: 0.283
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp1_optuna_fc_only_trial_20_epoch_1_kappa_0.283.jpg
Modelo guardado en: /kaggle/working/models/exp1_optuna_fc_only_trial_20_20260429_132040.pth

'/kaggle/working/exp1_optuna_fc_only_optuna_backup_part1.db'

In [ ]:
best_exp1 = study_exp1.best_trial

print("Mejor trial exp1:", best_exp1.number)
print("Mejor QWK exp1:", best_exp1.value)
print("Mejores hiperparámetros exp1:", best_exp1.params)

### Experimento 2 — Fine-tuning de layer4 (FC + layer4, batch = 32)

En este experimento se realiza fine-tuning parcial del modelo, entrenando:

- la capa fully connected final (`fc`);
- la última capa convolucional (`layer4`) de ResNet50.

Se mantiene el tamaño de batch en 32 y se optimizan mediante Optuna:

- learning rate (en un rango más bajo);
- momentum;
- número de epochs.

Se utiliza un rango de learning rate más pequeño que en el Experimento 1 por el entrenamiento de capas más profundas.

In [29]:
EXP_NAME = "exp2_optuna_fc_layer4"

def optuna_train_exp2(trial):
    print(f"\nTRIAL {trial.number}")

    lr = trial.suggest_float("lr", 1e-6, 1e-4, log=True)
    momentum = trial.suggest_float("momentum", 0.85, 0.98)
    epochs = trial.suggest_int("epochs", 4, 6)

    model = build_resnet50_model(
        num_classes=5,
        unfreeze_layer4=True,
        unfreeze_layer3=False
    )

    criterion = nn.CrossEntropyLoss()

    model, kappa, history, model_path, cm_path = train_val(
        model,
        criterion,
        {"train": train_dataloader, "val": val_dataloader},
        {"train": train_dataset, "val": val_dataset},
        device,
        epochs,
        lr,
        momentum,
        f"{EXP_NAME}_trial_{trial.number}"
    )

    results.append({
        "experiment": EXP_NAME,
        "trial": trial.number,
        "lr": lr,
        "momentum": momentum,
        "epochs": epochs,
        "kappa": kappa,
        "model_path": model_path,
        "cm_path": cm_path
    })

    all_histories.append(history)

    trial.set_user_attr("model_path", model_path)
    trial.set_user_attr("cm_path", cm_path)

    return kappa


study_exp2 = optuna.create_study(
    direction="maximize",
    study_name=EXP_NAME,
    storage=f"sqlite:///{OPTUNA_DB}",
    load_if_exists=True
)

study_exp2.optimize(optuna_train_exp2, n_trials=20)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)
shutil.copy(OPTUNA_DB, f"/kaggle/working/{EXP_NAME}_optuna_backup.db")

print("Experimento 2 finalizado y respaldado.")

[I 2026-04-29 14:33:31,895] Using an existing study with name 'exp2_optuna_fc_layer4' instead of creating a new one.

TRIAL 13
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.12it/s]

Train Loss: 1.4705 Acc: 31.05% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.72it/s]

Val Loss: 1.4230 Acc: 32.86% Kappa: 0.224

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4170 Acc: 34.57% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.62it/s]

Val Loss: 1.4088 Acc: 34.05% Kappa: 0.253

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.3989 Acc: 36.03% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.61it/s]

Val Loss: 1.4012 Acc: 35.11% Kappa: 0.253

Epoch 3/3
----------

100%|██████████| 367/367 [01:00<00:00,  6.09it/s]

Train Loss: 1.3872 Acc: 37.06% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.3971 Acc: 34.87% Kappa: 0.261

[I 2026-04-29 14:38:16,752] Trial 13 finished with value: 0.26110524266821544 and parameters: {'lr': 9.62061662086514e-05, 'momentum': 0.9746263644368561, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

Training complete in 4m 44s
Best val Acc: 34.87%
Best val Kappa: 0.261
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_13_epoch_3_kappa_0.261.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_13_20260429_143816.pth

TRIAL 14
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.12it/s]

Train Loss: 1.5174 Acc: 27.05% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4630 Acc: 31.66% Kappa: 0.136

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4489 Acc: 31.81% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.64it/s]

Val Loss: 1.4357 Acc: 33.23% Kappa: 0.188

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4306 Acc: 33.86% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4230 Acc: 34.36% Kappa: 0.232

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4192 Acc: 35.26% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.4143 Acc: 34.63% Kappa: 0.250

Training complete in 4m 43s
Best val Acc: 34.63%
Best val Kappa: 0.250
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_14_epoch_3_kappa_0.250.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_14_20260429_144300.pth

[I 2026-04-29 14:43:00,447] Trial 14 finished with value: 0.24959052922769598 and parameters: {'lr': 2.8174783994607524e-05, 'momentum': 0.9785228845400303, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

TRIAL 15
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4902 Acc: 29.58% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4391 Acc: 31.73% Kappa: 0.162

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4270 Acc: 34.49% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4189 Acc: 33.13% Kappa: 0.219

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4130 Acc: 35.54% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4096 Acc: 34.29% Kappa: 0.247

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4020 Acc: 35.96% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4043 Acc: 34.49% Kappa: 0.261

Training complete in 4m 43s
Best val Acc: 34.49%
Best val Kappa: 0.261
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_15_epoch_3_kappa_0.261.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_15_20260429_144743.pth

[I 2026-04-29 14:47:43,803] Trial 15 finished with value: 0.26063198735354043 and parameters: {'lr': 9.879704252352236e-05, 'momentum': 0.9538615117470826, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

TRIAL 16
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5228 Acc: 28.53% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.4694 Acc: 31.66% Kappa: 0.139

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4571 Acc: 32.57% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4435 Acc: 32.96% Kappa: 0.203

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4365 Acc: 33.59% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4301 Acc: 32.65% Kappa: 0.217

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4253 Acc: 34.10% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.61it/s]

Val Loss: 1.4219 Acc: 33.33% Kappa: 0.239

Training complete in 4m 43s
Best val Acc: 33.33%
Best val Kappa: 0.239
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_16_epoch_3_kappa_0.239.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_16_20260429_145227.pth

[I 2026-04-29 14:52:27,423] Trial 16 finished with value: 0.2393292778987216 and parameters: {'lr': 4.0805340778090195e-05, 'momentum': 0.9568432647029443, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

TRIAL 17
Epoch 0/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5970 Acc: 23.55% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.5696 Acc: 27.87% Kappa: 0.046

Epoch 1/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5527 Acc: 27.53% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.69it/s]

Val Loss: 1.5356 Acc: 29.65% Kappa: 0.088

Epoch 2/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5260 Acc: 28.64% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.5147 Acc: 30.26% Kappa: 0.110

Epoch 3/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5067 Acc: 29.30% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.72it/s]

Val Loss: 1.4983 Acc: 30.60% Kappa: 0.125

Epoch 4/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4929 Acc: 29.74% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4873 Acc: 30.88% Kappa: 0.147

[I 2026-04-29 14:58:21,486] Trial 17 finished with value: 0.14699144532376396 and parameters: {'lr': 6.495194683917646e-06, 'momentum': 0.9561836177849122, 'epochs': 5}. Best is trial 10 with value: 0.29111580868405584.

Training complete in 5m 53s
Best val Acc: 30.88%
Best val Kappa: 0.147
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_17_epoch_4_kappa_0.147.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_17_20260429_145821.pth

TRIAL 18
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.5221 Acc: 28.40% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.4690 Acc: 32.11% Kappa: 0.145

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4564 Acc: 32.22% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.68it/s]

Val Loss: 1.4412 Acc: 33.20% Kappa: 0.194

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4371 Acc: 33.29% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4288 Acc: 33.64% Kappa: 0.211

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.12it/s]

Train Loss: 1.4265 Acc: 34.37% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4211 Acc: 34.56% Kappa: 0.239

[I 2026-04-29 15:03:05,512] Trial 18 finished with value: 0.23908348965241666 and parameters: {'lr': 5.272557080408035e-05, 'momentum': 0.9452091762962997, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

Training complete in 4m 43s
Best val Acc: 34.56%
Best val Kappa: 0.239
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_18_epoch_3_kappa_0.239.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_18_20260429_150305.pth

TRIAL 19
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.5393 Acc: 26.41% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.62it/s]

Val Loss: 1.4860 Acc: 29.75% Kappa: 0.111

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4684 Acc: 30.92% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.64it/s]

Val Loss: 1.4555 Acc: 32.17% Kappa: 0.189

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4462 Acc: 32.88% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.76it/s]

Val Loss: 1.4393 Acc: 33.03% Kappa: 0.215

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4344 Acc: 33.67% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4321 Acc: 33.57% Kappa: 0.236

[I 2026-04-29 15:07:49,100] Trial 19 finished with value: 0.2360784437867013 and parameters: {'lr': 2.444253812675105e-05, 'momentum': 0.967817914374311, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

Training complete in 4m 43s
Best val Acc: 33.57%
Best val Kappa: 0.236
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_19_epoch_3_kappa_0.236.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_19_20260429_150748.pth

TRIAL 20
Epoch 0/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5820 Acc: 23.04% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.5654 Acc: 24.84% Kappa: 0.023

Epoch 1/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5475 Acc: 26.46% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]

Val Loss: 1.5373 Acc: 26.82% Kappa: 0.045

Epoch 2/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5253 Acc: 27.85% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.68it/s]

Val Loss: 1.5190 Acc: 27.84% Kappa: 0.060

Epoch 3/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.5091 Acc: 29.04% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.64it/s]

Val Loss: 1.5056 Acc: 28.93% Kappa: 0.082

Epoch 4/4
----------

100%|██████████| 367/367 [00:59<00:00,  6.12it/s]

Train Loss: 1.4957 Acc: 30.07% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.4933 Acc: 29.51% Kappa: 0.079

Training complete in 5m 53s
Best val Acc: 28.93%
Best val Kappa: 0.082
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_20_epoch_3_kappa_0.082.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_20_20260429_151342.pth

[I 2026-04-29 15:13:43,042] Trial 20 finished with value: 0.08150551630789293 and parameters: {'lr': 7.528054947596134e-06, 'momentum': 0.9392443721356556, 'epochs': 5}. Best is trial 10 with value: 0.29111580868405584.

TRIAL 21
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4982 Acc: 28.88% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.69it/s]

Val Loss: 1.4457 Acc: 32.28% Kappa: 0.192

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4338 Acc: 32.81% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4234 Acc: 33.95% Kappa: 0.243

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4170 Acc: 34.77% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.71it/s]

Val Loss: 1.4148 Acc: 34.02% Kappa: 0.248

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4064 Acc: 35.97% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4074 Acc: 34.70% Kappa: 0.254

[I 2026-04-29 15:18:26,364] Trial 21 finished with value: 0.25395656141583656 and parameters: {'lr': 6.473877200709889e-05, 'momentum': 0.9651993145972273, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

Training complete in 4m 43s
Best val Acc: 34.70%
Best val Kappa: 0.254
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_21_epoch_3_kappa_0.254.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_21_20260429_151826.pth

TRIAL 22
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4752 Acc: 30.21% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.4205 Acc: 34.02% Kappa: 0.255

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4130 Acc: 34.90% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.66it/s]

Val Loss: 1.4088 Acc: 35.01% Kappa: 0.275

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.3983 Acc: 36.20% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4011 Acc: 35.65% Kappa: 0.282

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.3848 Acc: 37.18% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.76it/s]

Val Loss: 1.3980 Acc: 34.83% Kappa: 0.272

Training complete in 4m 42s
Best val Acc: 35.65%
Best val Kappa: 0.282
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_22_epoch_2_kappa_0.282.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_22_20260429_152309.pth

[I 2026-04-29 15:23:09,554] Trial 22 finished with value: 0.28230637064410646 and parameters: {'lr': 9.032782943198443e-05, 'momentum': 0.9786699131071085, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

TRIAL 23
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.12it/s]

Train Loss: 1.5217 Acc: 27.94% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.70it/s]

Val Loss: 1.4628 Acc: 31.01% Kappa: 0.161

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4480 Acc: 32.91% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.62it/s]

Val Loss: 1.4355 Acc: 32.82% Kappa: 0.218

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4301 Acc: 33.56% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.4244 Acc: 33.85% Kappa: 0.234

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4196 Acc: 34.41% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.67it/s]

Val Loss: 1.4153 Acc: 33.95% Kappa: 0.261

[I 2026-04-29 15:27:53,696] Trial 23 finished with value: 0.2611242611638065 and parameters: {'lr': 3.0025579376851997e-05, 'momentum': 0.9753972303164816, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

Training complete in 4m 43s
Best val Acc: 33.95%
Best val Kappa: 0.261
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_23_epoch_3_kappa_0.261.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_23_20260429_152753.pth

TRIAL 24
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.12it/s]

Train Loss: 1.4871 Acc: 29.85% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.59it/s]

Val Loss: 1.4419 Acc: 32.00% Kappa: 0.195

Epoch 1/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4305 Acc: 33.66% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.63it/s]

Val Loss: 1.4218 Acc: 33.61% Kappa: 0.234

Epoch 2/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.13it/s]

Train Loss: 1.4139 Acc: 35.29% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.65it/s]

Val Loss: 1.4116 Acc: 34.02% Kappa: 0.253

Epoch 3/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.14it/s]

Train Loss: 1.4028 Acc: 36.10% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.75it/s]

Val Loss: 1.4067 Acc: 34.60% Kappa: 0.263

[I 2026-04-29 15:32:37,458] Trial 24 finished with value: 0.2631940403543219 and parameters: {'lr': 7.51578346281862e-05, 'momentum': 0.9650997384379242, 'epochs': 4}. Best is trial 10 with value: 0.29111580868405584.

Training complete in 4m 43s
Best val Acc: 34.60%
Best val Kappa: 0.263
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_24_epoch_3_kappa_0.263.jpg
Modelo guardado en: /kaggle/working/models/exp2_optuna_fc_layer4_trial_24_20260429_153237.pth

TRIAL 25
Epoch 0/3
----------

100%|██████████| 367/367 [00:59<00:00,  6.12it/s]

Train Loss: 1.4932 Acc: 29.85% Kappa: nan

100%|██████████| 92/92 [00:10<00:00,  8.77it/s]

Val Loss: 1.4380 Acc: 33.13% Kappa: 0.196

Epoch 1/3
----------

 41%|████      | 150/367 [00:24<00:35,  6.05it/s]
[W 2026-04-29 15:34:13,543] Trial 25 failed with parameters: {'lr': 4.220207443000859e-05, 'momentum': 0.9798144646230492, 'epochs': 4} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_57/234170156.py", line 18, in optuna_train_exp2
    model, kappa, history, model_path, cm_path = train_val(
                                                 ^^^^^^^^^^
  File "/tmp/ipykernel_57/1710094246.py", line 58, in train_val
    running_loss += loss.item() * inputs.size(0)
                    ^^^^^^^^^^^
KeyboardInterrupt
[W 2026-04-29 15:34:13,545] Trial 25 failed with value None.

KeyboardInterrupt:

In [30]:
print("Cantidad de trials:", len(study_exp2.trials))
print("Mejor trial:", study_exp2.best_trial)

Cantidad de trials: 26
Mejor trial: FrozenTrial(number=10, state=<TrialState.COMPLETE: 1>, values=[0.29111580868405584], datetime_start=datetime.datetime(2026, 4, 29, 14, 22, 3, 269096), datetime_complete=datetime.datetime(2026, 4, 29, 14, 26, 46, 455024), params={'lr': 9.854087684449751e-05, 'momentum': 0.9789049342924199, 'epochs': 4}, user_attrs={'cm_path': '/kaggle/working/confusion_matrices/exp2_optuna_fc_layer4_trial_10_epoch_3_kappa_0.291.jpg', 'model_path': '/kaggle/working/models/exp2_optuna_fc_layer4_trial_10_20260429_142646.pth'}, system_attrs={}, intermediate_values={}, distributions={'lr': FloatDistribution(high=0.0001, log=True, low=1e-06, step=None), 'momentum': FloatDistribution(high=0.98, log=False, low=0.85, step=None), 'epochs': IntDistribution(high=6, log=False, low=4, step=1)}, trial_id=32, value=None)

El mejor desempeño obtenido fue:

- **QWK ≈ 0.291**
- learning rate ≈ 9.85e-05  
- momentum ≈ 0.979  
- epochs = 4

### Experimento 3 — Fine-tuning de layer4 con batch size 16

En este experimento se mantiene la estrategia de fine-tuning parcial del Experimento 2, entrenando la capa final (`fc`) y `layer4`.

La diferencia principal es que se reduce el tamaño de batch de 32 a 16.

Esta modificación busca evaluar si un batch más pequeño mejora la generalización del modelo. 

Se optimizan mediante Optuna:

- learning rate;
- momentum;
- número de epochs.

In [31]:
EXP_NAME = "exp3_optuna_fc_layer4_batch16"

BATCH_SIZE_EXP3 = 16
train_ds3, val_ds3, train_dl3, val_dl3 = create_dataloaders(
    new_train_directory,
    new_val_directory,
    BATCH_SIZE_EXP3,
    NUM_WORKERS
)

def optuna_train_exp3(trial):
    print(f"\nTRIAL {trial.number}")

    lr = trial.suggest_float("lr", 1e-5, 5e-4, log=True)
    momentum = trial.suggest_float("momentum", 0.80, 0.95)
    epochs = trial.suggest_int("epochs", 5, 8)

    model = build_resnet50_model(5, True, False)

    criterion = nn.CrossEntropyLoss()

    model, kappa, history, model_path, cm_path = train_val(
        model, criterion,
        {"train": train_dl3, "val": val_dl3},
        {"train": train_data, "val": val_data},
        device, epochs, lr, momentum,
        f"{EXP_NAME}_trial_{trial.number}"
    )

    trial.set_user_attr("model_path", model_path)
    trial.set_user_attr("cm_path", cm_path)

    return kappa


study_exp3 = optuna.create_study(
    direction="maximize",
    study_name=EXP_NAME,
    storage=f"sqlite:///{OPTUNA_DB}",
    load_if_exists=True
)

study_exp3.optimize(optuna_train_exp3, n_trials=20)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)
shutil.copy(OPTUNA_DB, f"/kaggle/working/{EXP_NAME}_optuna_backup.db")

print("Experimento 3 finalizado y respaldado.")

[I 2026-04-29 15:34:42,689] A new study created in RDB with name: exp3_optuna_fc_layer4_batch16

TRIAL 0
Epoch 0/6
----------

100%|██████████| 733/733 [01:04<00:00, 11.43it/s]

Train Loss: 1.4994 Acc: 26.95% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.97it/s]

Val Loss: 1.4545 Acc: 29.51% Kappa: 0.134

Epoch 1/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.70it/s]

Train Loss: 1.4379 Acc: 30.15% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.42it/s]

Val Loss: 1.4250 Acc: 31.44% Kappa: 0.178

Epoch 2/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.4159 Acc: 31.62% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.16it/s]

Val Loss: 1.4092 Acc: 32.01% Kappa: 0.200

Epoch 3/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.91it/s]

Train Loss: 1.4030 Acc: 32.63% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.17it/s]

Val Loss: 1.4002 Acc: 32.88% Kappa: 0.227

Epoch 4/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3975 Acc: 32.78% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.05it/s]

Val Loss: 1.3957 Acc: 32.71% Kappa: 0.234

Epoch 5/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.82it/s]

Train Loss: 1.3903 Acc: 33.58% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3901 Acc: 33.44% Kappa: 0.247

Epoch 6/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.3876 Acc: 33.97% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.11it/s]

Val Loss: 1.3864 Acc: 33.68% Kappa: 0.253

[I 2026-04-29 15:43:15,975] Trial 0 finished with value: 0.25347616599674105 and parameters: {'lr': 4.158811841126308e-05, 'momentum': 0.8822424050838248, 'epochs': 7}. Best is trial 0 with value: 0.25347616599674105.

Training complete in 8m 33s
Best val Acc: 33.68%
Best val Kappa: 0.253
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_0_epoch_6_kappa_0.253.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_0_20260429_154315.pth

TRIAL 1
Epoch 0/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.4632 Acc: 28.66% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.4185 Acc: 32.28% Kappa: 0.186

Epoch 1/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.4070 Acc: 32.36% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.00it/s]

Val Loss: 1.3942 Acc: 32.94% Kappa: 0.236

Epoch 2/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.78it/s]

Train Loss: 1.3906 Acc: 34.07% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.07it/s]

Val Loss: 1.3847 Acc: 33.38% Kappa: 0.261

Epoch 3/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3821 Acc: 34.15% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3794 Acc: 33.61% Kappa: 0.268

Epoch 4/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3765 Acc: 35.03% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.12it/s]

Val Loss: 1.3766 Acc: 33.61% Kappa: 0.256

Training complete in 6m 5s
Best val Acc: 33.61%
Best val Kappa: 0.268
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_1_epoch_3_kappa_0.268.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_1_20260429_154921.pth

[I 2026-04-29 15:49:22,060] Trial 1 finished with value: 0.26822598952880405 and parameters: {'lr': 6.273938293126151e-05, 'momentum': 0.9201948163693892, 'epochs': 5}. Best is trial 1 with value: 0.26822598952880405.

TRIAL 2
Epoch 0/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.4908 Acc: 27.92% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.13it/s]

Val Loss: 1.4486 Acc: 30.94% Kappa: 0.126

Epoch 1/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.82it/s]

Train Loss: 1.4305 Acc: 31.00% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.4188 Acc: 32.01% Kappa: 0.162

Epoch 2/5
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.4128 Acc: 32.30% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.25it/s]

Val Loss: 1.4058 Acc: 33.11% Kappa: 0.209

Epoch 3/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.90it/s]

Train Loss: 1.3997 Acc: 33.14% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.18it/s]

Val Loss: 1.3990 Acc: 33.61% Kappa: 0.233

Epoch 4/5
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.3947 Acc: 33.88% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.08it/s]

Val Loss: 1.3939 Acc: 33.44% Kappa: 0.233

Epoch 5/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.3889 Acc: 33.45% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.14it/s]

Val Loss: 1.3880 Acc: 33.81% Kappa: 0.249

[I 2026-04-29 15:56:40,137] Trial 2 finished with value: 0.24915913602396345 and parameters: {'lr': 3.077818174986711e-05, 'momentum': 0.9248005532139985, 'epochs': 6}. Best is trial 1 with value: 0.26822598952880405.

Training complete in 7m 17s
Best val Acc: 33.81%
Best val Kappa: 0.249
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_2_epoch_5_kappa_0.249.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_2_20260429_155639.pth

TRIAL 3
Epoch 0/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.82it/s]

Train Loss: 1.5289 Acc: 25.18% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.19it/s]

Val Loss: 1.4910 Acc: 28.84% Kappa: 0.066

Epoch 1/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.94it/s]

Train Loss: 1.4668 Acc: 29.25% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.08it/s]

Val Loss: 1.4536 Acc: 29.98% Kappa: 0.106

Epoch 2/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.4407 Acc: 31.12% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.25it/s]

Val Loss: 1.4361 Acc: 30.41% Kappa: 0.141

Epoch 3/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.4261 Acc: 31.99% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.15it/s]

Val Loss: 1.4231 Acc: 31.04% Kappa: 0.168

Epoch 4/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.4171 Acc: 32.27% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.24it/s]

Val Loss: 1.4167 Acc: 32.08% Kappa: 0.192

Epoch 5/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.4098 Acc: 32.75% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.13it/s]

Val Loss: 1.4090 Acc: 32.28% Kappa: 0.193

Epoch 6/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.4060 Acc: 32.72% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.06it/s]

Val Loss: 1.4049 Acc: 32.31% Kappa: 0.207

[I 2026-04-29 16:05:10,800] Trial 3 finished with value: 0.2065087462462759 and parameters: {'lr': 1.1874562492914607e-05, 'momentum': 0.9380405149109883, 'epochs': 7}. Best is trial 1 with value: 0.26822598952880405.

Training complete in 8m 30s
Best val Acc: 32.31%
Best val Kappa: 0.207
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_3_epoch_6_kappa_0.207.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_3_20260429_160510.pth

TRIAL 4
Epoch 0/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4747 Acc: 27.40% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.07it/s]

Val Loss: 1.4289 Acc: 30.64% Kappa: 0.153

Epoch 1/4
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.4144 Acc: 31.92% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.27it/s]

Val Loss: 1.4061 Acc: 32.21% Kappa: 0.208

Epoch 2/4
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.3966 Acc: 32.92% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.18it/s]

Val Loss: 1.3939 Acc: 32.34% Kappa: 0.227

Epoch 3/4
----------

100%|██████████| 733/733 [01:01<00:00, 11.82it/s]

Train Loss: 1.3880 Acc: 33.64% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.07it/s]

Val Loss: 1.3868 Acc: 33.11% Kappa: 0.253

Epoch 4/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.3802 Acc: 34.72% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.06it/s]
[I 2026-04-29 16:11:16,055] Trial 4 finished with value: 0.2530631470378094 and parameters: {'lr': 0.0001219853457414152, 'momentum': 0.8216494177630659, 'epochs': 5}. Best is trial 1 with value: 0.26822598952880405.

Val Loss: 1.3823 Acc: 33.71% Kappa: 0.246

Training complete in 6m 5s
Best val Acc: 33.11%
Best val Kappa: 0.253
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_4_epoch_3_kappa_0.253.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_4_20260429_161115.pth

TRIAL 5
Epoch 0/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4232 Acc: 31.45% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3833 Acc: 34.24% Kappa: 0.269

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.3805 Acc: 34.39% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.20it/s]

Val Loss: 1.3698 Acc: 34.84% Kappa: 0.283

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.3637 Acc: 35.49% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3655 Acc: 35.45% Kappa: 0.277

Epoch 3/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3535 Acc: 35.91% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.07it/s]

Val Loss: 1.3633 Acc: 34.74% Kappa: 0.283

Epoch 4/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3458 Acc: 36.57% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3623 Acc: 36.05% Kappa: 0.284

Epoch 5/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.3375 Acc: 37.36% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3603 Acc: 34.98% Kappa: 0.291

Epoch 6/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.3315 Acc: 38.01% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.08it/s]

Val Loss: 1.3612 Acc: 35.11% Kappa: 0.305

Epoch 7/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3229 Acc: 38.61% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.12it/s]

Val Loss: 1.3600 Acc: 35.78% Kappa: 0.297

Training complete in 9m 44s
Best val Acc: 35.11%
Best val Kappa: 0.305
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_5_epoch_6_kappa_0.305.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_5_20260429_162100.pth

[I 2026-04-29 16:21:00,577] Trial 5 finished with value: 0.30519426911431435 and parameters: {'lr': 0.0004076322177108788, 'momentum': 0.8339322586180025, 'epochs': 8}. Best is trial 5 with value: 0.30519426911431435.

TRIAL 6
Epoch 0/5
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4830 Acc: 26.93% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.18it/s]

Val Loss: 1.4338 Acc: 29.71% Kappa: 0.114

Epoch 1/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.95it/s]

Train Loss: 1.4224 Acc: 31.18% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.23it/s]

Val Loss: 1.4092 Acc: 31.94% Kappa: 0.176

Epoch 2/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.4035 Acc: 32.74% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 16.98it/s]

Val Loss: 1.3962 Acc: 33.01% Kappa: 0.215

Epoch 3/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.90it/s]

Train Loss: 1.3941 Acc: 33.12% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.33it/s]

Val Loss: 1.3889 Acc: 33.48% Kappa: 0.222

Epoch 4/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.3856 Acc: 34.12% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.08it/s]

Val Loss: 1.3832 Acc: 33.61% Kappa: 0.242

Epoch 5/5
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.3796 Acc: 34.13% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.03it/s]

Val Loss: 1.3781 Acc: 34.01% Kappa: 0.253

[I 2026-04-29 16:28:18,231] Trial 6 finished with value: 0.2533494185220214 and parameters: {'lr': 9.901054881651699e-05, 'momentum': 0.8184398272915091, 'epochs': 6}. Best is trial 5 with value: 0.30519426911431435.

Training complete in 7m 17s
Best val Acc: 34.01%
Best val Kappa: 0.253
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_6_epoch_5_kappa_0.253.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_6_20260429_162818.pth

TRIAL 7
Epoch 0/4
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.4886 Acc: 27.80% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.25it/s]

Val Loss: 1.4363 Acc: 30.61% Kappa: 0.162

Epoch 1/4
----------

100%|██████████| 733/733 [01:01<00:00, 11.96it/s]

Train Loss: 1.4240 Acc: 31.47% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.26it/s]

Val Loss: 1.4068 Acc: 32.88% Kappa: 0.209

Epoch 2/4
----------

100%|██████████| 733/733 [01:01<00:00, 11.91it/s]

Train Loss: 1.4058 Acc: 32.81% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.21it/s]

Val Loss: 1.3954 Acc: 33.34% Kappa: 0.252

Epoch 3/4
----------

100%|██████████| 733/733 [01:01<00:00, 11.90it/s]

Train Loss: 1.3955 Acc: 33.10% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.20it/s]

Val Loss: 1.3889 Acc: 33.61% Kappa: 0.244

Epoch 4/4
----------

100%|██████████| 733/733 [01:01<00:00, 11.88it/s]

Train Loss: 1.3883 Acc: 33.69% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.20it/s]

Val Loss: 1.3829 Acc: 33.98% Kappa: 0.265

[I 2026-04-29 16:34:21,977] Trial 7 finished with value: 0.2653506297162601 and parameters: {'lr': 0.00010163045328263057, 'momentum': 0.8053403913235655, 'epochs': 5}. Best is trial 5 with value: 0.30519426911431435.

Training complete in 6m 3s
Best val Acc: 33.98%
Best val Kappa: 0.265
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_7_epoch_4_kappa_0.265.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_7_20260429_163421.pth

TRIAL 8
Epoch 0/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.4798 Acc: 27.37% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.03it/s]

Val Loss: 1.4422 Acc: 30.51% Kappa: 0.152

Epoch 1/5
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4277 Acc: 30.67% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.23it/s]

Val Loss: 1.4167 Acc: 32.11% Kappa: 0.179

Epoch 2/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.95it/s]

Train Loss: 1.4099 Acc: 31.95% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.24it/s]

Val Loss: 1.4045 Acc: 33.24% Kappa: 0.213

Epoch 3/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.4010 Acc: 32.31% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3971 Acc: 33.81% Kappa: 0.242

Epoch 4/5
----------

100%|██████████| 733/733 [01:02<00:00, 11.78it/s]

Train Loss: 1.3940 Acc: 33.35% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3915 Acc: 33.44% Kappa: 0.246

Epoch 5/5
----------

100%|██████████| 733/733 [01:01<00:00, 11.85it/s]

Train Loss: 1.3849 Acc: 34.22% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.19it/s]

Val Loss: 1.3877 Acc: 33.38% Kappa: 0.245

Training complete in 7m 17s
Best val Acc: 33.44%
Best val Kappa: 0.246
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_8_epoch_4_kappa_0.246.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_8_20260429_164139.pth

[I 2026-04-29 16:41:39,646] Trial 8 finished with value: 0.24563214776411757 and parameters: {'lr': 3.813575681345678e-05, 'momentum': 0.9148120558321456, 'epochs': 6}. Best is trial 5 with value: 0.30519426911431435.

TRIAL 9
Epoch 0/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.5272 Acc: 26.34% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.20it/s]

Val Loss: 1.4866 Acc: 28.61% Kappa: 0.079

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.97it/s]

Train Loss: 1.4672 Acc: 29.14% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.32it/s]

Val Loss: 1.4515 Acc: 30.31% Kappa: 0.122

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.4412 Acc: 30.07% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.07it/s]

Val Loss: 1.4306 Acc: 31.21% Kappa: 0.153

Epoch 3/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.4268 Acc: 30.73% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.24it/s]

Val Loss: 1.4203 Acc: 31.58% Kappa: 0.170

Epoch 4/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.99it/s]

Train Loss: 1.4169 Acc: 31.67% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.27it/s]

Val Loss: 1.4127 Acc: 32.01% Kappa: 0.191

Epoch 5/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.4101 Acc: 32.10% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.06it/s]

Val Loss: 1.4066 Acc: 32.61% Kappa: 0.205

Epoch 6/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4044 Acc: 32.52% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.12it/s]

Val Loss: 1.4016 Acc: 33.18% Kappa: 0.210

Epoch 7/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3995 Acc: 32.57% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3989 Acc: 33.48% Kappa: 0.215

[I 2026-04-29 16:51:22,724] Trial 9 finished with value: 0.21526868039616132 and parameters: {'lr': 2.0801507435545283e-05, 'momentum': 0.8950327507671567, 'epochs': 8}. Best is trial 5 with value: 0.30519426911431435.

Training complete in 9m 42s
Best val Acc: 33.48%
Best val Kappa: 0.215
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_9_epoch_7_kappa_0.215.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_9_20260429_165122.pth

TRIAL 10
Epoch 0/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4197 Acc: 31.67% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.16it/s]

Val Loss: 1.3867 Acc: 33.51% Kappa: 0.275

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.3746 Acc: 34.80% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.17it/s]

Val Loss: 1.3743 Acc: 33.34% Kappa: 0.268

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.91it/s]

Train Loss: 1.3607 Acc: 35.59% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3682 Acc: 34.04% Kappa: 0.272

Epoch 3/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.77it/s]

Train Loss: 1.3486 Acc: 36.58% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3672 Acc: 34.11% Kappa: 0.275

Epoch 4/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.88it/s]

Train Loss: 1.3384 Acc: 36.88% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.28it/s]

Val Loss: 1.3647 Acc: 34.58% Kappa: 0.294

Epoch 5/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.94it/s]

Train Loss: 1.3286 Acc: 37.98% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.32it/s]

Val Loss: 1.3673 Acc: 33.74% Kappa: 0.279

Epoch 6/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.3251 Acc: 38.14% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.04it/s]

Val Loss: 1.3666 Acc: 35.21% Kappa: 0.293

Epoch 7/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.78it/s]

Train Loss: 1.3170 Acc: 39.13% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.27it/s]

Val Loss: 1.3655 Acc: 34.28% Kappa: 0.304

[I 2026-04-29 17:01:04,646] Trial 10 finished with value: 0.30351926993278255 and parameters: {'lr': 0.0004370068984690972, 'momentum': 0.849036250282289, 'epochs': 8}. Best is trial 5 with value: 0.30519426911431435.

Training complete in 9m 41s
Best val Acc: 34.28%
Best val Kappa: 0.304
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_10_epoch_7_kappa_0.304.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_10_20260429_170104.pth

TRIAL 11
Epoch 0/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.88it/s]

Train Loss: 1.4199 Acc: 30.92% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.07it/s]

Val Loss: 1.3881 Acc: 33.64% Kappa: 0.253

Epoch 1/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3783 Acc: 34.28% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.18it/s]

Val Loss: 1.3771 Acc: 33.81% Kappa: 0.273

Epoch 2/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3635 Acc: 35.55% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3702 Acc: 34.14% Kappa: 0.283

Epoch 3/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3551 Acc: 36.11% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.08it/s]

Val Loss: 1.3672 Acc: 34.41% Kappa: 0.279

Epoch 4/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3446 Acc: 37.44% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.20it/s]

Val Loss: 1.3679 Acc: 33.74% Kappa: 0.289

Epoch 5/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.3380 Acc: 37.77% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.13it/s]

Val Loss: 1.3654 Acc: 34.48% Kappa: 0.288

Epoch 6/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3304 Acc: 38.21% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.11it/s]

Val Loss: 1.3655 Acc: 34.44% Kappa: 0.289

Epoch 7/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.3250 Acc: 38.62% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.02it/s]

Val Loss: 1.3645 Acc: 35.25% Kappa: 0.299

[I 2026-04-29 17:10:48,863] Trial 11 finished with value: 0.2986923825042713 and parameters: {'lr': 0.00037079597114723537, 'momentum': 0.850730080337016, 'epochs': 8}. Best is trial 5 with value: 0.30519426911431435.

Training complete in 9m 44s
Best val Acc: 35.25%
Best val Kappa: 0.299
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_11_epoch_7_kappa_0.299.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_11_20260429_171048.pth

TRIAL 12
Epoch 0/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.71it/s]

Train Loss: 1.4173 Acc: 31.52% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.19it/s]

Val Loss: 1.3813 Acc: 33.94% Kappa: 0.244

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.96it/s]

Train Loss: 1.3745 Acc: 34.49% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.34it/s]

Val Loss: 1.3709 Acc: 33.88% Kappa: 0.268

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.3595 Acc: 35.51% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.31it/s]

Val Loss: 1.3658 Acc: 34.38% Kappa: 0.263

Epoch 3/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.93it/s]

Train Loss: 1.3448 Acc: 36.99% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3613 Acc: 34.71% Kappa: 0.284

Epoch 4/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.3397 Acc: 37.54% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.29it/s]

Val Loss: 1.3612 Acc: 34.94% Kappa: 0.302

Epoch 5/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.96it/s]

Train Loss: 1.3286 Acc: 38.26% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.26it/s]

Val Loss: 1.3638 Acc: 35.01% Kappa: 0.281

Epoch 6/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.3184 Acc: 39.13% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.17it/s]

Val Loss: 1.3671 Acc: 34.01% Kappa: 0.300

Epoch 7/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.91it/s]

Train Loss: 1.3108 Acc: 39.77% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.25it/s]

Val Loss: 1.3644 Acc: 35.31% Kappa: 0.307

[I 2026-04-29 17:20:30,593] Trial 12 finished with value: 0.3072919449041095 and parameters: {'lr': 0.0004995548828358864, 'momentum': 0.8454086799690226, 'epochs': 8}. Best is trial 12 with value: 0.3072919449041095.

Training complete in 9m 41s
Best val Acc: 35.31%
Best val Kappa: 0.307
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_12_epoch_7_kappa_0.307.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_12_20260429_172030.pth

TRIAL 13
Epoch 0/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.4395 Acc: 30.29% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.05it/s]

Val Loss: 1.4016 Acc: 32.21% Kappa: 0.231

Epoch 1/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.78it/s]

Train Loss: 1.3908 Acc: 33.71% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.35it/s]

Val Loss: 1.3823 Acc: 33.81% Kappa: 0.261

Epoch 2/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.3774 Acc: 34.45% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 16.96it/s]

Val Loss: 1.3756 Acc: 33.41% Kappa: 0.262

Epoch 3/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3690 Acc: 34.90% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.18it/s]

Val Loss: 1.3705 Acc: 34.11% Kappa: 0.269

Epoch 4/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.3586 Acc: 36.48% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.01it/s]

Val Loss: 1.3674 Acc: 34.08% Kappa: 0.278

Epoch 5/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.3524 Acc: 36.27% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.22it/s]

Val Loss: 1.3660 Acc: 34.51% Kappa: 0.279

Epoch 6/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.3465 Acc: 37.04% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.08it/s]

Val Loss: 1.3650 Acc: 34.01% Kappa: 0.268

Training complete in 8m 30s
Best val Acc: 34.51%
Best val Kappa: 0.279
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_13_epoch_5_kappa_0.279.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_13_20260429_172901.pth

[I 2026-04-29 17:29:01,378] Trial 13 finished with value: 0.27861852086352956 and parameters: {'lr': 0.00022545300187698622, 'momentum': 0.8532617955850925, 'epochs': 7}. Best is trial 12 with value: 0.3072919449041095.

TRIAL 14
Epoch 0/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.78it/s]

Train Loss: 1.4509 Acc: 28.89% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.14it/s]

Val Loss: 1.4026 Acc: 33.61% Kappa: 0.223

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.93it/s]

Train Loss: 1.3971 Acc: 33.23% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.34it/s]

Val Loss: 1.3850 Acc: 34.21% Kappa: 0.258

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.3831 Acc: 34.37% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.02it/s]

Val Loss: 1.3754 Acc: 34.58% Kappa: 0.283

Epoch 3/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.3732 Acc: 34.43% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.11it/s]

Val Loss: 1.3693 Acc: 34.68% Kappa: 0.278

Epoch 4/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.3653 Acc: 35.77% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.14it/s]

Val Loss: 1.3666 Acc: 34.74% Kappa: 0.280

Epoch 5/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.3595 Acc: 35.91% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.13it/s]

Val Loss: 1.3648 Acc: 34.61% Kappa: 0.272

Epoch 6/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3555 Acc: 36.38% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3620 Acc: 34.08% Kappa: 0.278

Epoch 7/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.3497 Acc: 36.75% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.05it/s]

Val Loss: 1.3612 Acc: 35.18% Kappa: 0.289

[I 2026-04-29 17:38:44,759] Trial 14 finished with value: 0.28879810926193394 and parameters: {'lr': 0.00019955389382511315, 'momentum': 0.8353112252655883, 'epochs': 8}. Best is trial 12 with value: 0.3072919449041095.

Training complete in 9m 43s
Best val Acc: 35.18%
Best val Kappa: 0.289
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_14_epoch_7_kappa_0.289.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_14_20260429_173844.pth

TRIAL 15
Epoch 0/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4321 Acc: 30.07% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.17it/s]

Val Loss: 1.3926 Acc: 33.61% Kappa: 0.240

Epoch 1/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.3845 Acc: 34.08% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.37it/s]

Val Loss: 1.3776 Acc: 33.88% Kappa: 0.281

Epoch 2/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.3693 Acc: 35.26% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.35it/s]

Val Loss: 1.3685 Acc: 34.08% Kappa: 0.281

Epoch 3/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.3602 Acc: 35.94% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.31it/s]

Val Loss: 1.3659 Acc: 34.71% Kappa: 0.266

Epoch 4/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.3514 Acc: 36.17% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3641 Acc: 34.51% Kappa: 0.292

Epoch 5/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.3448 Acc: 36.74% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.33it/s]

Val Loss: 1.3620 Acc: 34.78% Kappa: 0.273

Epoch 6/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.3377 Acc: 37.45% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3594 Acc: 35.18% Kappa: 0.296

[I 2026-04-29 17:47:14,564] Trial 15 finished with value: 0.2958933405491253 and parameters: {'lr': 0.0002636517072669081, 'momentum': 0.8689216185392683, 'epochs': 7}. Best is trial 12 with value: 0.3072919449041095.

Training complete in 8m 29s
Best val Acc: 35.18%
Best val Kappa: 0.296
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_15_epoch_6_kappa_0.296.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_15_20260429_174714.pth

TRIAL 16
Epoch 0/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.4225 Acc: 31.34% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.30it/s]

Val Loss: 1.3897 Acc: 32.94% Kappa: 0.266

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.86it/s]

Train Loss: 1.3784 Acc: 34.46% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.00it/s]

Val Loss: 1.3751 Acc: 33.48% Kappa: 0.268

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.94it/s]

Train Loss: 1.3649 Acc: 35.52% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.31it/s]

Val Loss: 1.3693 Acc: 34.18% Kappa: 0.273

Epoch 3/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.3543 Acc: 36.10% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.23it/s]

Val Loss: 1.3667 Acc: 34.38% Kappa: 0.285

Epoch 4/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.3444 Acc: 37.23% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 16.98it/s]

Val Loss: 1.3659 Acc: 34.48% Kappa: 0.312

Epoch 5/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.93it/s]

Train Loss: 1.3394 Acc: 37.31% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.21it/s]

Val Loss: 1.3632 Acc: 35.41% Kappa: 0.305

Epoch 6/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.3327 Acc: 38.07% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.06it/s]

Val Loss: 1.3627 Acc: 34.88% Kappa: 0.302

Epoch 7/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.75it/s]

Train Loss: 1.3243 Acc: 38.63% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3660 Acc: 35.11% Kappa: 0.295

Training complete in 9m 42s
Best val Acc: 34.48%
Best val Kappa: 0.312
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_16_epoch_4_kappa_0.312.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_16_20260429_175656.pth

[I 2026-04-29 17:56:57,062] Trial 16 finished with value: 0.3117360983701776 and parameters: {'lr': 0.00041194164591519024, 'momentum': 0.8311181411720225, 'epochs': 8}. Best is trial 16 with value: 0.3117360983701776.

TRIAL 17
Epoch 0/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.84it/s]

Train Loss: 1.4615 Acc: 27.76% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.04it/s]

Val Loss: 1.4215 Acc: 31.04% Kappa: 0.149

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.89it/s]

Train Loss: 1.4100 Acc: 31.37% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.26it/s]

Val Loss: 1.3998 Acc: 32.61% Kappa: 0.220

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.88it/s]

Train Loss: 1.3945 Acc: 33.60% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3888 Acc: 32.84% Kappa: 0.243

Epoch 3/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.81it/s]

Train Loss: 1.3823 Acc: 34.17% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.20it/s]

Val Loss: 1.3817 Acc: 34.28% Kappa: 0.260

Epoch 4/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.3740 Acc: 35.01% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.14it/s]

Val Loss: 1.3766 Acc: 34.11% Kappa: 0.264

Epoch 5/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.83it/s]

Train Loss: 1.3685 Acc: 35.43% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.10it/s]

Val Loss: 1.3744 Acc: 34.38% Kappa: 0.268

Epoch 6/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3665 Acc: 35.42% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.09it/s]

Val Loss: 1.3715 Acc: 34.24% Kappa: 0.280

Epoch 7/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.82it/s]

Train Loss: 1.3599 Acc: 35.58% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.26it/s]

Val Loss: 1.3686 Acc: 35.01% Kappa: 0.290

[I 2026-04-29 18:06:41,478] Trial 17 finished with value: 0.2896387006355434 and parameters: {'lr': 0.00015826237189672617, 'momentum': 0.800061318705719, 'epochs': 8}. Best is trial 16 with value: 0.3117360983701776.

Training complete in 9m 44s
Best val Acc: 35.01%
Best val Kappa: 0.290
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_17_epoch_7_kappa_0.290.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_17_20260429_180641.pth

TRIAL 18
Epoch 0/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.96it/s]

Train Loss: 1.4273 Acc: 30.97% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.25it/s]

Val Loss: 1.3902 Acc: 33.38% Kappa: 0.242

Epoch 1/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.85it/s]

Train Loss: 1.3815 Acc: 34.28% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.15it/s]

Val Loss: 1.3727 Acc: 33.74% Kappa: 0.261

Epoch 2/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.3644 Acc: 35.73% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.21it/s]

Val Loss: 1.3676 Acc: 34.28% Kappa: 0.281

Epoch 3/6
----------

100%|██████████| 733/733 [01:01<00:00, 12.00it/s]

Train Loss: 1.3579 Acc: 35.94% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.35it/s]

Val Loss: 1.3648 Acc: 34.24% Kappa: 0.287

Epoch 4/6
----------

100%|██████████| 733/733 [01:01<00:00, 11.87it/s]

Train Loss: 1.3465 Acc: 36.89% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.03it/s]

Val Loss: 1.3657 Acc: 34.04% Kappa: 0.283

Epoch 5/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.77it/s]

Train Loss: 1.3405 Acc: 37.70% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.05it/s]

Val Loss: 1.3620 Acc: 34.74% Kappa: 0.289

Epoch 6/6
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3317 Acc: 37.74% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.06it/s]
[I 2026-04-29 18:15:11,179] Trial 18 finished with value: 0.28932298899032105 and parameters: {'lr': 0.00029540007571241466, 'momentum': 0.8731953847322255, 'epochs': 7}. Best is trial 16 with value: 0.3117360983701776.

Val Loss: 1.3628 Acc: 34.58% Kappa: 0.287

Training complete in 8m 29s
Best val Acc: 34.74%
Best val Kappa: 0.289
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_18_epoch_5_kappa_0.289.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_18_20260429_181510.pth

TRIAL 19
Epoch 0/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.79it/s]

Train Loss: 1.4229 Acc: 30.87% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.14it/s]

Val Loss: 1.3855 Acc: 33.38% Kappa: 0.230

Epoch 1/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.94it/s]

Train Loss: 1.3769 Acc: 34.48% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.30it/s]

Val Loss: 1.3747 Acc: 34.08% Kappa: 0.276

Epoch 2/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.90it/s]

Train Loss: 1.3641 Acc: 35.39% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.17it/s]

Val Loss: 1.3677 Acc: 34.64% Kappa: 0.288

Epoch 3/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.80it/s]

Train Loss: 1.3505 Acc: 36.74% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.17it/s]

Val Loss: 1.3645 Acc: 34.54% Kappa: 0.292

Epoch 4/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.91it/s]

Train Loss: 1.3428 Acc: 36.87% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.32it/s]

Val Loss: 1.3633 Acc: 35.58% Kappa: 0.296

Epoch 5/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.88it/s]

Train Loss: 1.3343 Acc: 37.95% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 16.99it/s]

Val Loss: 1.3650 Acc: 34.58% Kappa: 0.288

Epoch 6/7
----------

100%|██████████| 733/733 [01:02<00:00, 11.78it/s]

Train Loss: 1.3272 Acc: 38.39% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.15it/s]

Val Loss: 1.3642 Acc: 36.11% Kappa: 0.305

Epoch 7/7
----------

100%|██████████| 733/733 [01:01<00:00, 11.92it/s]

Train Loss: 1.3176 Acc: 38.79% Kappa: nan

100%|██████████| 184/184 [00:10<00:00, 17.29it/s]

Val Loss: 1.3634 Acc: 35.38% Kappa: 0.289

Training complete in 9m 41s
Best val Acc: 36.11%
Best val Kappa: 0.305
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_19_epoch_6_kappa_0.305.jpg
Modelo guardado en: /kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_19_20260429_182453.pth

[I 2026-04-29 18:24:53,371] Trial 19 finished with value: 0.3046099070150169 and parameters: {'lr': 0.00045672184599701186, 'momentum': 0.8335942872210407, 'epochs': 8}. Best is trial 16 with value: 0.3117360983701776.

In [34]:
print("Cantidad de trials:", len(study_exp3.trials))
print("Mejor trial:", study_exp3.best_trial)

Cantidad de trials: 20
Mejor trial: FrozenTrial(number=16, state=<TrialState.COMPLETE: 1>, values=[0.3117360983701776], datetime_start=datetime.datetime(2026, 4, 29, 17, 47, 14, 572869), datetime_complete=datetime.datetime(2026, 4, 29, 17, 56, 57, 48824), params={'lr': 0.00041194164591519024, 'momentum': 0.8311181411720225, 'epochs': 8}, user_attrs={'cm_path': '/kaggle/working/confusion_matrices/exp3_optuna_fc_layer4_batch16_trial_16_epoch_4_kappa_0.312.jpg', 'model_path': '/kaggle/working/models/exp3_optuna_fc_layer4_batch16_trial_16_20260429_175656.pth'}, system_attrs={}, intermediate_values={}, distributions={'lr': FloatDistribution(high=0.0005, log=True, low=1e-05, step=None), 'momentum': FloatDistribution(high=0.95, log=False, low=0.8, step=None), 'epochs': IntDistribution(high=8, log=False, low=5, step=1)}, trial_id=64, value=None)

### Resultados del Experimento 3

El mejor desempeño se obtuvo en el trial 16:

- **QWK ≈ 0.312**
- learning rate ≈ 4.12e-4
- momentum ≈ 0.831
- epochs = 8
- batch size = 16

Este fue el mejor resultado obtenido durante la optimización.

### Experimento 4 — Fine-tuning de layer4 con learning rate fino

En este experimento se mantiene la configuración del Experimento 3:

- entrenamiento de la capa final (`fc`);
- fine-tuning de `layer4`;
- batch size = 16.

La diferencia principal es que se restringe el rango del learning rate a valores más bajos. Esta estrategia busca evaluar si un ajuste más conservador de los pesos preentrenados mejora la estabilidad del entrenamiento.

Se optimizan mediante Optuna:

- learning rate en un rango fino;
- momentum;
- número de epochs.

In [29]:
EXP_NAME = "exp4_optuna_fc_layer4_batch16"

BATCH_SIZE_EXP4 = 16

train_ds4, val_ds4, train_dl4, val_dl4 = create_dataloaders(
    new_train_directory,
    new_val_directory,
    BATCH_SIZE_EXP4,
    NUM_WORKERS
)

def optuna_train_exp4(trial):
    print(f"\nTRIAL {trial.number}")

    lr = trial.suggest_float("lr", 5e-6, 2e-4, log=True)
    momentum = trial.suggest_float("momentum", 0.88, 0.98)
    epochs = trial.suggest_int("epochs", 5, 8)

    model = build_resnet50_model(
        num_classes=5,
        unfreeze_layer4=True,
        unfreeze_layer3=False
    )

    criterion = nn.CrossEntropyLoss()

    model, kappa, history, model_path, cm_path = train_val(
        model,
        criterion,
        {"train": train_dl4, "val": val_dl4},
        {"train": train_ds4, "val": val_ds4},
        device,
        epochs,
        lr,
        momentum,
        f"{EXP_NAME}_trial_{trial.number}"
    )

    results.append({
        "experiment": EXP_NAME,
        "trial": trial.number,
        "batch_size": BATCH_SIZE_EXP4,
        "lr": lr,
        "momentum": momentum,
        "epochs": epochs,
        "kappa": kappa,
        "model_path": model_path,
        "cm_path": cm_path
    })

    all_histories.append(history)

    trial.set_user_attr("model_path", model_path)
    trial.set_user_attr("cm_path", cm_path)

    return kappa


study_exp4 = optuna.create_study(
    direction="maximize",
    study_name=EXP_NAME,
    storage=f"sqlite:///{OPTUNA_DB}",
    load_if_exists=True
)

study_exp4.optimize(optuna_train_exp4, n_trials=20)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)
shutil.copy(OPTUNA_DB, f"/kaggle/working/{EXP_NAME}_optuna_backup.db")

print("Experimento 4 finalizado y respaldado.")

[I 2026-04-30 11:20:34,258] A new study created in RDB with name: exp4_optuna_fc_layer4_batch16

TRIAL 0
Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 179MB/s]

Epoch 0/4
----------

100%|██████████| 733/733 [00:50<00:00, 14.42it/s]

Train Loss: 1.4838 Acc: 29.74% Kappa: nan

100%|██████████| 184/184 [00:08<00:00, 20.76it/s]

Val Loss: 1.4370 Acc: 32.55% Kappa: 0.220

Epoch 1/4
----------

100%|██████████| 733/733 [00:51<00:00, 14.28it/s]

Train Loss: 1.4295 Acc: 33.70% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.4182 Acc: 33.85% Kappa: 0.258

Epoch 2/4
----------

100%|██████████| 733/733 [00:53<00:00, 13.65it/s]

Train Loss: 1.4113 Acc: 35.53% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.13it/s]

Val Loss: 1.4106 Acc: 34.70% Kappa: 0.276

Epoch 3/4
----------

100%|██████████| 733/733 [00:52<00:00, 13.87it/s]

Train Loss: 1.4030 Acc: 36.02% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.4051 Acc: 35.21% Kappa: 0.276

Epoch 4/4
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.3936 Acc: 36.32% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.95it/s]

Val Loss: 1.4007 Acc: 35.55% Kappa: 0.281

[I 2026-04-30 11:25:44,857] Trial 0 finished with value: 0.28118861490361147 and parameters: {'lr': 0.00013251362082432195, 'momentum': 0.9006579286090007, 'epochs': 5}. Best is trial 0 with value: 0.28118861490361147.

Training complete in 5m 9s
Best val Acc: 35.55%
Best val Kappa: 0.281
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_0_epoch_4_kappa_0.281.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_0_20260430_112544.pth

TRIAL 1
Epoch 0/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.5294 Acc: 27.10% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.64it/s]

Val Loss: 1.4884 Acc: 29.48% Kappa: 0.095

Epoch 1/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4659 Acc: 30.90% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.4545 Acc: 31.56% Kappa: 0.174

Epoch 2/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4447 Acc: 32.94% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.72it/s]

Val Loss: 1.4413 Acc: 32.55% Kappa: 0.213

Epoch 3/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4344 Acc: 33.10% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.83it/s]

Val Loss: 1.4342 Acc: 33.13% Kappa: 0.234

Epoch 4/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4271 Acc: 34.46% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.81it/s]

Val Loss: 1.4275 Acc: 33.98% Kappa: 0.255

Epoch 5/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4212 Acc: 34.46% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.87it/s]
[I 2026-04-30 11:32:01,644] Trial 1 finished with value: 0.2548048819886507 and parameters: {'lr': 1.6327335213521988e-05, 'momentum': 0.9606105528720514, 'epochs': 6}. Best is trial 0 with value: 0.28118861490361147.

Val Loss: 1.4228 Acc: 33.95% Kappa: 0.253

Training complete in 6m 16s
Best val Acc: 33.98%
Best val Kappa: 0.255
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_1_epoch_4_kappa_0.255.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_1_20260430_113201.pth

TRIAL 2
Epoch 0/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.5129 Acc: 30.19% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.99it/s]

Val Loss: 1.4686 Acc: 31.76% Kappa: 0.166

Epoch 1/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4507 Acc: 33.10% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.99it/s]

Val Loss: 1.4441 Acc: 33.74% Kappa: 0.208

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4323 Acc: 33.92% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.99it/s]

Val Loss: 1.4307 Acc: 33.95% Kappa: 0.214

Epoch 3/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4238 Acc: 34.30% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.84it/s]

Val Loss: 1.4231 Acc: 33.85% Kappa: 0.227

Epoch 4/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4166 Acc: 34.49% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.98it/s]

Val Loss: 1.4174 Acc: 34.19% Kappa: 0.241

Epoch 5/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4099 Acc: 35.26% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.4135 Acc: 34.63% Kappa: 0.250

Epoch 6/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4060 Acc: 35.55% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.85it/s]

Val Loss: 1.4124 Acc: 34.19% Kappa: 0.248

Epoch 7/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.4018 Acc: 36.00% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.01it/s]

Val Loss: 1.4095 Acc: 34.94% Kappa: 0.263

[I 2026-04-30 11:40:22,392] Trial 2 finished with value: 0.2628154908268213 and parameters: {'lr': 5.647189596074955e-05, 'momentum': 0.8968850968607245, 'epochs': 8}. Best is trial 0 with value: 0.28118861490361147.

Training complete in 8m 20s
Best val Acc: 34.94%
Best val Kappa: 0.263
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_2_epoch_7_kappa_0.263.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_2_20260430_114022.pth

TRIAL 3
Epoch 0/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.5676 Acc: 25.23% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.5355 Acc: 26.99% Kappa: 0.038

Epoch 1/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.5120 Acc: 28.45% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4999 Acc: 29.27% Kappa: 0.074

Epoch 2/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4853 Acc: 30.20% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.83it/s]

Val Loss: 1.4792 Acc: 30.98% Kappa: 0.119

Epoch 3/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4701 Acc: 30.65% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4689 Acc: 31.63% Kappa: 0.149

Epoch 4/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4597 Acc: 31.59% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.86it/s]

Val Loss: 1.4570 Acc: 32.69% Kappa: 0.190

Epoch 5/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4520 Acc: 32.75% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.90it/s]

Val Loss: 1.4512 Acc: 33.20% Kappa: 0.199

Epoch 6/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4451 Acc: 32.35% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.03it/s]

Val Loss: 1.4456 Acc: 33.40% Kappa: 0.209

[I 2026-04-30 11:47:41,407] Trial 3 finished with value: 0.20889662034280443 and parameters: {'lr': 6.722679734537109e-06, 'momentum': 0.9556244159701173, 'epochs': 7}. Best is trial 0 with value: 0.28118861490361147.

Training complete in 7m 18s
Best val Acc: 33.40%
Best val Kappa: 0.209
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_3_epoch_6_kappa_0.209.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_3_20260430_114741.pth

TRIAL 4
Epoch 0/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.5570 Acc: 26.88% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.00it/s]

Val Loss: 1.5218 Acc: 29.38% Kappa: 0.119

Epoch 1/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4977 Acc: 30.13% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.97it/s]

Val Loss: 1.4882 Acc: 31.87% Kappa: 0.150

Epoch 2/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4752 Acc: 30.99% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.89it/s]

Val Loss: 1.4674 Acc: 32.41% Kappa: 0.165

Epoch 3/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4610 Acc: 32.32% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.77it/s]

Val Loss: 1.4552 Acc: 32.58% Kappa: 0.194

Epoch 4/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4494 Acc: 32.63% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.99it/s]

Val Loss: 1.4487 Acc: 32.51% Kappa: 0.195

Epoch 5/6
----------

100%|██████████| 733/733 [00:52<00:00, 13.85it/s]

Train Loss: 1.4439 Acc: 32.92% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.91it/s]

Val Loss: 1.4429 Acc: 33.06% Kappa: 0.200

Epoch 6/6
----------

100%|██████████| 733/733 [00:52<00:00, 13.83it/s]

Train Loss: 1.4378 Acc: 33.66% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.97it/s]

Val Loss: 1.4373 Acc: 33.44% Kappa: 0.212

[I 2026-04-30 11:55:00,347] Trial 4 finished with value: 0.2117045593636645 and parameters: {'lr': 1.3044144380300866e-05, 'momentum': 0.9316057004413659, 'epochs': 7}. Best is trial 0 with value: 0.28118861490361147.

Training complete in 7m 18s
Best val Acc: 33.44%
Best val Kappa: 0.212
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_4_epoch_6_kappa_0.212.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_4_20260430_115500.pth

TRIAL 5
Epoch 0/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.5959 Acc: 24.78% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.89it/s]

Val Loss: 1.5682 Acc: 27.81% Kappa: 0.021

Epoch 1/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.5520 Acc: 27.01% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.5350 Acc: 28.42% Kappa: 0.023

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.5240 Acc: 27.99% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.80it/s]

Val Loss: 1.5141 Acc: 29.38% Kappa: 0.055

Epoch 3/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.5064 Acc: 28.99% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.99it/s]

Val Loss: 1.4986 Acc: 29.96% Kappa: 0.075

Epoch 4/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.4922 Acc: 29.87% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.02it/s]

Val Loss: 1.4873 Acc: 29.92% Kappa: 0.083

Epoch 5/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.4825 Acc: 30.38% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.02it/s]

Val Loss: 1.4773 Acc: 30.40% Kappa: 0.115

Epoch 6/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.83it/s]

Train Loss: 1.4751 Acc: 31.00% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.99it/s]

Val Loss: 1.4726 Acc: 30.47% Kappa: 0.133

Epoch 7/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.4686 Acc: 30.96% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.86it/s]

Val Loss: 1.4656 Acc: 31.01% Kappa: 0.142

[I 2026-04-30 12:03:21,320] Trial 5 finished with value: 0.1417545900496534 and parameters: {'lr': 7.26357834374155e-06, 'momentum': 0.9071510841112792, 'epochs': 8}. Best is trial 0 with value: 0.28118861490361147.

Training complete in 8m 20s
Best val Acc: 31.01%
Best val Kappa: 0.142
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_5_epoch_7_kappa_0.142.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_5_20260430_120321.pth

TRIAL 6
Epoch 0/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4384 Acc: 32.53% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.97it/s]

Val Loss: 1.4112 Acc: 34.46% Kappa: 0.269

Epoch 1/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.3951 Acc: 36.59% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.01it/s]

Val Loss: 1.4028 Acc: 35.35% Kappa: 0.272

Epoch 2/6
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.3761 Acc: 37.73% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.67it/s]

Val Loss: 1.3950 Acc: 36.40% Kappa: 0.309

Epoch 3/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.3590 Acc: 38.74% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.3950 Acc: 35.14% Kappa: 0.299

Epoch 4/6
----------

100%|██████████| 733/733 [00:52<00:00, 13.86it/s]

Train Loss: 1.3413 Acc: 40.70% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.3996 Acc: 36.23% Kappa: 0.293

Epoch 5/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.3269 Acc: 41.24% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.85it/s]

Val Loss: 1.4051 Acc: 36.17% Kappa: 0.307

Epoch 6/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.3105 Acc: 42.87% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.71it/s]
[I 2026-04-30 12:10:38,946] Trial 6 finished with value: 0.30852112095218387 and parameters: {'lr': 0.00014184777695228404, 'momentum': 0.9773997523560716, 'epochs': 7}. Best is trial 6 with value: 0.30852112095218387.

Val Loss: 1.4133 Acc: 36.20% Kappa: 0.304

Training complete in 7m 17s
Best val Acc: 36.40%
Best val Kappa: 0.309
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_6_epoch_2_kappa_0.309.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_6_20260430_121038.pth

TRIAL 7
Epoch 0/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.5204 Acc: 29.56% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4730 Acc: 31.08% Kappa: 0.136

Epoch 1/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4595 Acc: 31.23% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.63it/s]

Val Loss: 1.4454 Acc: 33.09% Kappa: 0.185

Epoch 2/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4392 Acc: 32.87% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.91it/s]

Val Loss: 1.4313 Acc: 33.27% Kappa: 0.213

Epoch 3/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4294 Acc: 34.43% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.95it/s]

Val Loss: 1.4226 Acc: 33.95% Kappa: 0.239

Epoch 4/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4204 Acc: 34.14% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.4187 Acc: 34.15% Kappa: 0.246

Epoch 5/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4163 Acc: 35.32% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.73it/s]

Val Loss: 1.4142 Acc: 34.46% Kappa: 0.255

Epoch 6/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4108 Acc: 35.07% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.78it/s]
[I 2026-04-30 12:17:58,182] Trial 7 finished with value: 0.25488431026537106 and parameters: {'lr': 2.5071076059667785e-05, 'momentum': 0.9473727011582483, 'epochs': 7}. Best is trial 6 with value: 0.30852112095218387.

Val Loss: 1.4117 Acc: 34.39% Kappa: 0.251

Training complete in 7m 19s
Best val Acc: 34.46%
Best val Kappa: 0.255
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_7_epoch_5_kappa_0.255.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_7_20260430_121758.pth

TRIAL 8
Epoch 0/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.4966 Acc: 28.96% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.84it/s]

Val Loss: 1.4483 Acc: 31.25% Kappa: 0.156

Epoch 1/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4382 Acc: 32.74% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.4261 Acc: 32.48% Kappa: 0.198

Epoch 2/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.69it/s]

Train Loss: 1.4224 Acc: 34.41% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.82it/s]

Val Loss: 1.4176 Acc: 33.81% Kappa: 0.234

Epoch 3/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4126 Acc: 35.24% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.77it/s]

Val Loss: 1.4117 Acc: 34.02% Kappa: 0.240

Epoch 4/5
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.4041 Acc: 35.94% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4063 Acc: 34.77% Kappa: 0.263

Epoch 5/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.3989 Acc: 36.40% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.71it/s]

Val Loss: 1.4022 Acc: 35.18% Kappa: 0.272

[I 2026-04-30 12:24:15,359] Trial 8 finished with value: 0.2724375651029022 and parameters: {'lr': 7.947941152954912e-05, 'momentum': 0.9175427657166088, 'epochs': 6}. Best is trial 6 with value: 0.30852112095218387.

Training complete in 6m 17s
Best val Acc: 35.18%
Best val Kappa: 0.272
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_8_epoch_5_kappa_0.272.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_8_20260430_122415.pth

TRIAL 9
Epoch 0/4
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.5778 Acc: 24.52% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.84it/s]

Val Loss: 1.5414 Acc: 25.76% Kappa: 0.014

Epoch 1/4
----------

100%|██████████| 733/733 [00:53<00:00, 13.77it/s]

Train Loss: 1.5159 Acc: 28.33% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.78it/s]

Val Loss: 1.5034 Acc: 28.08% Kappa: 0.053

Epoch 2/4
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4886 Acc: 29.78% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.85it/s]

Val Loss: 1.4803 Acc: 29.34% Kappa: 0.090

Epoch 3/4
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4719 Acc: 31.28% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.90it/s]

Val Loss: 1.4649 Acc: 30.47% Kappa: 0.124

Epoch 4/4
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4600 Acc: 31.23% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.75it/s]

Val Loss: 1.4574 Acc: 30.67% Kappa: 0.147

[I 2026-04-30 12:29:29,659] Trial 9 finished with value: 0.14746359802556241 and parameters: {'lr': 5.57741334245586e-06, 'momentum': 0.9640904239050334, 'epochs': 5}. Best is trial 6 with value: 0.30852112095218387.

Training complete in 5m 14s
Best val Acc: 30.67%
Best val Kappa: 0.147
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_9_epoch_4_kappa_0.147.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_9_20260430_122929.pth

TRIAL 10
Epoch 0/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4758 Acc: 30.80% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.82it/s]

Val Loss: 1.4331 Acc: 33.98% Kappa: 0.206

Epoch 1/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4252 Acc: 34.56% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.83it/s]

Val Loss: 1.4165 Acc: 34.70% Kappa: 0.255

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4091 Acc: 35.54% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.82it/s]

Val Loss: 1.4089 Acc: 35.28% Kappa: 0.255

Epoch 3/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4000 Acc: 35.82% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.97it/s]

Val Loss: 1.4037 Acc: 35.28% Kappa: 0.273

Epoch 4/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.3915 Acc: 36.68% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.4020 Acc: 35.38% Kappa: 0.267

Epoch 5/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.83it/s]

Train Loss: 1.3884 Acc: 36.99% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.97it/s]

Val Loss: 1.3993 Acc: 35.14% Kappa: 0.277

Epoch 6/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.3807 Acc: 37.51% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.3980 Acc: 35.76% Kappa: 0.285

Epoch 7/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.3753 Acc: 38.08% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.83it/s]

Val Loss: 1.3967 Acc: 35.76% Kappa: 0.297

[I 2026-04-30 12:37:50,779] Trial 10 finished with value: 0.29660126063525183 and parameters: {'lr': 0.00016195419823681915, 'momentum': 0.8803959715364206, 'epochs': 8}. Best is trial 6 with value: 0.30852112095218387.

Training complete in 8m 20s
Best val Acc: 35.76%
Best val Kappa: 0.297
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_10_epoch_7_kappa_0.297.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_10_20260430_123750.pth

TRIAL 11
Epoch 0/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.77it/s]

Train Loss: 1.4728 Acc: 30.33% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.91it/s]

Val Loss: 1.4310 Acc: 33.54% Kappa: 0.228

Epoch 1/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4193 Acc: 34.84% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.90it/s]

Val Loss: 1.4133 Acc: 33.98% Kappa: 0.249

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4048 Acc: 35.78% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.63it/s]

Val Loss: 1.4063 Acc: 34.43% Kappa: 0.271

Epoch 3/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.3949 Acc: 36.56% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.4015 Acc: 34.43% Kappa: 0.262

Epoch 4/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3856 Acc: 36.80% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.3985 Acc: 34.77% Kappa: 0.287

Epoch 5/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3821 Acc: 37.23% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.82it/s]

Val Loss: 1.3970 Acc: 34.60% Kappa: 0.270

Epoch 6/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.3742 Acc: 38.29% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.80it/s]

Val Loss: 1.3973 Acc: 34.83% Kappa: 0.273

Epoch 7/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.3669 Acc: 38.87% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.70it/s]
[I 2026-04-30 12:46:12,042] Trial 11 finished with value: 0.2867819650120109 and parameters: {'lr': 0.0001949248554264622, 'momentum': 0.8838157475678746, 'epochs': 8}. Best is trial 6 with value: 0.30852112095218387.

Val Loss: 1.3967 Acc: 35.24% Kappa: 0.283

Training complete in 8m 21s
Best val Acc: 34.77%
Best val Kappa: 0.287
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_11_epoch_4_kappa_0.287.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_11_20260430_124611.pth

TRIAL 12
Epoch 0/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4520 Acc: 32.56% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.4136 Acc: 34.32% Kappa: 0.251

Epoch 1/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4050 Acc: 35.75% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.85it/s]

Val Loss: 1.3997 Acc: 35.04% Kappa: 0.266

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.3884 Acc: 37.17% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.97it/s]

Val Loss: 1.3962 Acc: 35.62% Kappa: 0.274

Epoch 3/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.3769 Acc: 38.28% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.98it/s]

Val Loss: 1.3952 Acc: 35.35% Kappa: 0.291

Epoch 4/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.3670 Acc: 39.09% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.87it/s]

Val Loss: 1.3967 Acc: 35.69% Kappa: 0.305

Epoch 5/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3593 Acc: 39.61% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.83it/s]

Val Loss: 1.3934 Acc: 35.76% Kappa: 0.301

Epoch 6/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.3514 Acc: 40.07% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.3966 Acc: 35.72% Kappa: 0.290

Epoch 7/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.3385 Acc: 40.82% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.54it/s]
[I 2026-04-30 12:54:32,874] Trial 12 finished with value: 0.3045645692875044 and parameters: {'lr': 7.216850640561875e-05, 'momentum': 0.9782389102294835, 'epochs': 8}. Best is trial 6 with value: 0.30852112095218387.

Val Loss: 1.3999 Acc: 35.69% Kappa: 0.292

Training complete in 8m 20s
Best val Acc: 35.69%
Best val Kappa: 0.305
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_12_epoch_4_kappa_0.305.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_12_20260430_125432.pth

TRIAL 13
Epoch 0/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4546 Acc: 31.70% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.4138 Acc: 34.25% Kappa: 0.246

Epoch 1/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4044 Acc: 35.72% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.89it/s]

Val Loss: 1.4022 Acc: 35.04% Kappa: 0.277

Epoch 2/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.67it/s]

Train Loss: 1.3880 Acc: 37.16% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.87it/s]

Val Loss: 1.3991 Acc: 35.04% Kappa: 0.287

Epoch 3/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.3753 Acc: 37.67% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.99it/s]

Val Loss: 1.3993 Acc: 34.66% Kappa: 0.294

Epoch 4/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.3633 Acc: 38.68% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.96it/s]

Val Loss: 1.3978 Acc: 35.65% Kappa: 0.292

Epoch 5/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.3537 Acc: 39.38% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.85it/s]

Val Loss: 1.3948 Acc: 35.69% Kappa: 0.302

Epoch 6/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.3423 Acc: 40.45% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.98it/s]

Val Loss: 1.3984 Acc: 35.69% Kappa: 0.303

[I 2026-04-30 13:01:52,382] Trial 13 finished with value: 0.3029716813514881 and parameters: {'lr': 7.796971346496228e-05, 'momentum': 0.9795010710702848, 'epochs': 7}. Best is trial 6 with value: 0.30852112095218387.

Training complete in 7m 19s
Best val Acc: 35.69%
Best val Kappa: 0.303
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_13_epoch_6_kappa_0.303.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_13_20260430_130152.pth

TRIAL 14
Epoch 0/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4675 Acc: 30.65% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4239 Acc: 33.64% Kappa: 0.224

Epoch 1/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4135 Acc: 34.48% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.96it/s]

Val Loss: 1.4088 Acc: 34.83% Kappa: 0.264

Epoch 2/5
----------

100%|██████████| 733/733 [00:52<00:00, 13.83it/s]

Train Loss: 1.3991 Acc: 36.51% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4047 Acc: 34.49% Kappa: 0.267

Epoch 3/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.3871 Acc: 36.94% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.3992 Acc: 34.87% Kappa: 0.270

Epoch 4/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3791 Acc: 37.50% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.79it/s]

Val Loss: 1.3987 Acc: 34.87% Kappa: 0.272

Epoch 5/5
----------

100%|██████████| 733/733 [00:52<00:00, 13.83it/s]

Train Loss: 1.3726 Acc: 38.17% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.77it/s]

Val Loss: 1.3993 Acc: 35.21% Kappa: 0.285

[I 2026-04-30 13:08:08,564] Trial 14 finished with value: 0.28511185199436173 and parameters: {'lr': 5.012166858102933e-05, 'momentum': 0.9790916891244404, 'epochs': 6}. Best is trial 6 with value: 0.30852112095218387.

Training complete in 6m 16s
Best val Acc: 35.21%
Best val Kappa: 0.285
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_14_epoch_5_kappa_0.285.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_14_20260430_130808.pth

TRIAL 15
Epoch 0/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4666 Acc: 31.75% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.91it/s]

Val Loss: 1.4296 Acc: 33.13% Kappa: 0.212

Epoch 1/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.4222 Acc: 34.72% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.81it/s]

Val Loss: 1.4160 Acc: 33.91% Kappa: 0.271

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4059 Acc: 36.04% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.4078 Acc: 34.53% Kappa: 0.268

Epoch 3/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3952 Acc: 36.50% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4041 Acc: 35.35% Kappa: 0.287

Epoch 4/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.3879 Acc: 36.63% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.85it/s]

Val Loss: 1.4001 Acc: 35.14% Kappa: 0.294

Epoch 5/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.3800 Acc: 37.39% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.98it/s]

Val Loss: 1.3988 Acc: 35.48% Kappa: 0.273

Epoch 6/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.3752 Acc: 38.25% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.91it/s]

Val Loss: 1.3978 Acc: 35.52% Kappa: 0.271

Epoch 7/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.83it/s]

Train Loss: 1.3668 Acc: 38.55% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.72it/s]
[I 2026-04-30 13:16:28,886] Trial 15 finished with value: 0.29396363201251974 and parameters: {'lr': 0.00010781558553532541, 'momentum': 0.938313584149206, 'epochs': 8}. Best is trial 6 with value: 0.30852112095218387.

Val Loss: 1.3957 Acc: 35.38% Kappa: 0.288

Training complete in 8m 20s
Best val Acc: 35.14%
Best val Kappa: 0.294
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_15_epoch_4_kappa_0.294.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_15_20260430_131628.pth

TRIAL 16
Epoch 0/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4778 Acc: 31.16% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.86it/s]

Val Loss: 1.4339 Acc: 32.58% Kappa: 0.217

Epoch 1/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4252 Acc: 34.37% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4166 Acc: 34.32% Kappa: 0.253

Epoch 2/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.4115 Acc: 35.49% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4081 Acc: 34.49% Kappa: 0.272

Epoch 3/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.4020 Acc: 36.29% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.4045 Acc: 34.70% Kappa: 0.258

Epoch 4/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.3949 Acc: 36.75% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.83it/s]

Val Loss: 1.4017 Acc: 34.66% Kappa: 0.267

Epoch 5/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.3872 Acc: 37.22% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.90it/s]

Val Loss: 1.3977 Acc: 35.21% Kappa: 0.278

Epoch 6/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3835 Acc: 37.11% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.86it/s]

Val Loss: 1.3959 Acc: 35.01% Kappa: 0.286

[I 2026-04-30 13:23:47,456] Trial 16 finished with value: 0.2864319699913398 and parameters: {'lr': 4.072695288299648e-05, 'momentum': 0.9693251518073539, 'epochs': 7}. Best is trial 6 with value: 0.30852112095218387.

Training complete in 7m 18s
Best val Acc: 35.01%
Best val Kappa: 0.286
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_16_epoch_6_kappa_0.286.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_16_20260430_132347.pth

TRIAL 17
Epoch 0/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.4748 Acc: 30.99% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.04it/s]

Val Loss: 1.4302 Acc: 34.12% Kappa: 0.225

Epoch 1/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.4230 Acc: 34.39% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.4137 Acc: 34.70% Kappa: 0.240

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4074 Acc: 35.94% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.94it/s]

Val Loss: 1.4049 Acc: 34.83% Kappa: 0.262

Epoch 3/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.83it/s]

Train Loss: 1.3941 Acc: 36.46% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.90it/s]

Val Loss: 1.3993 Acc: 34.87% Kappa: 0.270

Epoch 4/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.3926 Acc: 36.12% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.98it/s]

Val Loss: 1.3980 Acc: 35.65% Kappa: 0.272

Epoch 5/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.85it/s]

Train Loss: 1.3818 Acc: 37.73% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.98it/s]

Val Loss: 1.3943 Acc: 35.21% Kappa: 0.273

Epoch 6/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.3773 Acc: 37.52% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.95it/s]

Val Loss: 1.3942 Acc: 35.93% Kappa: 0.287

Epoch 7/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.80it/s]

Train Loss: 1.3732 Acc: 38.58% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.3929 Acc: 35.72% Kappa: 0.288

[I 2026-04-30 13:32:08,068] Trial 17 finished with value: 0.28814324547353376 and parameters: {'lr': 8.042244013322793e-05, 'momentum': 0.9525698467155647, 'epochs': 8}. Best is trial 6 with value: 0.30852112095218387.

Training complete in 8m 20s
Best val Acc: 35.72%
Best val Kappa: 0.288
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_17_epoch_7_kappa_0.288.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_17_20260430_133207.pth

TRIAL 18
Epoch 0/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4905 Acc: 30.50% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.77it/s]

Val Loss: 1.4447 Acc: 32.51% Kappa: 0.196

Epoch 1/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4344 Acc: 33.50% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.93it/s]

Val Loss: 1.4254 Acc: 33.64% Kappa: 0.223

Epoch 2/6
----------

100%|██████████| 733/733 [00:52<00:00, 13.84it/s]

Train Loss: 1.4170 Acc: 34.73% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.96it/s]

Val Loss: 1.4149 Acc: 33.64% Kappa: 0.250

Epoch 3/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.83it/s]

Train Loss: 1.4085 Acc: 35.57% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.86it/s]

Val Loss: 1.4120 Acc: 33.98% Kappa: 0.260

Epoch 4/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.4027 Acc: 36.00% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.92it/s]

Val Loss: 1.4050 Acc: 34.70% Kappa: 0.267

Epoch 5/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3949 Acc: 36.83% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.89it/s]

Val Loss: 1.4033 Acc: 34.77% Kappa: 0.268

Epoch 6/6
----------

100%|██████████| 733/733 [00:53<00:00, 13.81it/s]

Train Loss: 1.3903 Acc: 36.87% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.81it/s]
[I 2026-04-30 13:39:26,956] Trial 18 finished with value: 0.2684975827309175 and parameters: {'lr': 2.8476774036575337e-05, 'momentum': 0.9707996421844096, 'epochs': 7}. Best is trial 6 with value: 0.30852112095218387.

Val Loss: 1.4008 Acc: 34.73% Kappa: 0.264

Training complete in 7m 18s
Best val Acc: 34.77%
Best val Kappa: 0.268
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_18_epoch_5_kappa_0.268.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_18_20260430_133926.pth

TRIAL 19
Epoch 0/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.4680 Acc: 30.62% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.64it/s]

Val Loss: 1.4277 Acc: 33.61% Kappa: 0.244

Epoch 1/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4185 Acc: 34.62% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.77it/s]

Val Loss: 1.4110 Acc: 34.39% Kappa: 0.264

Epoch 2/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.4027 Acc: 36.05% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.4049 Acc: 35.28% Kappa: 0.279

Epoch 3/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.77it/s]

Train Loss: 1.3925 Acc: 36.48% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.87it/s]

Val Loss: 1.4010 Acc: 35.41% Kappa: 0.266

Epoch 4/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.3833 Acc: 37.38% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.3971 Acc: 35.89% Kappa: 0.288

Epoch 5/5
----------

100%|██████████| 733/733 [00:53<00:00, 13.79it/s]

Train Loss: 1.3791 Acc: 37.64% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]
[I 2026-04-30 13:45:43,750] Trial 19 finished with value: 0.287681579625781 and parameters: {'lr': 0.00011181264366980306, 'momentum': 0.9436297548331631, 'epochs': 6}. Best is trial 6 with value: 0.30852112095218387.

Val Loss: 1.3954 Acc: 36.03% Kappa: 0.285

Training complete in 6m 16s
Best val Acc: 35.89%
Best val Kappa: 0.288
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_19_epoch_4_kappa_0.288.jpg
Modelo guardado en: /kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_19_20260430_134543.pth
Todo guardado ✔

In [56]:
print("Cantidad de trials:", len(study_exp4.trials))
print("Mejor trial:", study_exp4.best_trial)

Cantidad de trials: 20
Mejor trial: FrozenTrial(number=6, state=<TrialState.COMPLETE: 1>, values=[0.30852112095218387], datetime_start=datetime.datetime(2026, 4, 30, 12, 3, 21, 328225), datetime_complete=datetime.datetime(2026, 4, 30, 12, 10, 38, 929494), params={'lr': 0.00014184777695228404, 'momentum': 0.9773997523560716, 'epochs': 7}, user_attrs={'cm_path': '/kaggle/working/confusion_matrices/exp4_optuna_fc_layer4_batch16_trial_6_epoch_2_kappa_0.309.jpg', 'model_path': '/kaggle/working/models/exp4_optuna_fc_layer4_batch16_trial_6_20260430_121038.pth'}, system_attrs={}, intermediate_values={}, distributions={'lr': FloatDistribution(high=0.0002, log=True, low=5e-06, step=None), 'momentum': FloatDistribution(high=0.98, log=False, low=0.88, step=None), 'epochs': IntDistribution(high=8, log=False, low=5, step=1)}, trial_id=7, value=None)

### Resultados del Experimento 4

El mejor desempeño del Experimento 4 se obtuvo en el trial 6:

- **QWK ≈ 0.309**
- learning rate ≈ 1.42e-4
- momentum ≈ 0.977
- epochs = 7
- batch size = 16

Este resultado fue muy cercano al mejor desempeño del Experimento 3, aunque no lo superó.

### Experimentos de mejores hiperparámetros sin optuna

### Experimento manual 1 — Solo FC con hiperparámetros del Experimento 3

Se utilizan los mejores hiperparámetros encontrados en el Experimento 3:

- learning rate ≈ 4.1e-4  
- momentum ≈ 0.83  
- epochs = 8  
- batch size = 16  

Pero **sin fine-tuning de layer4**.

Este experimento permite evaluar si el desempeño del Experimento 3 se debe principalmente a los hiperparámetros o al ajuste de capas profundas.

In [65]:
EXP_NAME = "exp_manual_fc_only_best_exp3"

BATCH_SIZE_EXP7 = 16

train_ds7, val_ds7, train_dl7, val_dl7 = create_dataloaders(
    new_train_directory,
    new_val_directory,
    BATCH_SIZE_EXP7,
    NUM_WORKERS
)

EXP7_LR = 4.1e-4
EXP7_MOMENTUM = 0.83
EXP7_EPOCHS = 8

model = build_resnet50_model(
    num_classes=5,
    unfreeze_layer4=False,
    unfreeze_layer3=False
)

criterion = nn.CrossEntropyLoss()

model, kappa, history, model_path, cm_path = train_val(
    model,
    criterion,
    {"train": train_dl7, "val": val_dl7},
    {"train": train_ds7, "val": val_ds7},
    device,
    EXP7_EPOCHS,
    EXP7_LR,
    EXP7_MOMENTUM,
    EXP_NAME
)

results.append({
    "experiment": EXP_NAME,
    "trial": "manual_best_exp3_params",
    "batch_size": BATCH_SIZE_EXP7,
    "unfreeze_layer4": False,
    "unfreeze_layer3": False,
    "lr": EXP7_LR,
    "momentum": EXP7_MOMENTUM,
    "epochs": EXP7_EPOCHS,
    "kappa": kappa,
    "model_path": model_path,
    "cm_path": cm_path
})

all_histories.append(history)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)

print("Kappa exp7:", kappa)
print("Modelo:", model_path)
print("Matriz:", cm_path)

Epoch 0/7
----------

100%|██████████| 733/733 [00:43<00:00, 16.86it/s]

Train Loss: 1.4579 Acc: 32.16% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.36it/s]

Val Loss: 1.4246 Acc: 34.08% Kappa: 0.251

Epoch 1/7
----------

100%|██████████| 733/733 [00:44<00:00, 16.61it/s]

Train Loss: 1.4161 Acc: 34.25% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.68it/s]

Val Loss: 1.4121 Acc: 34.97% Kappa: 0.258

Epoch 2/7
----------

100%|██████████| 733/733 [00:43<00:00, 16.87it/s]

Train Loss: 1.4046 Acc: 35.42% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.68it/s]

Val Loss: 1.4082 Acc: 34.66% Kappa: 0.270

Epoch 3/7
----------

100%|██████████| 733/733 [00:42<00:00, 17.13it/s]

Train Loss: 1.3959 Acc: 36.38% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.59it/s]

Val Loss: 1.4050 Acc: 35.07% Kappa: 0.269

Epoch 4/7
----------

100%|██████████| 733/733 [00:43<00:00, 16.96it/s]

Train Loss: 1.3914 Acc: 36.60% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.75it/s]

Val Loss: 1.4021 Acc: 34.83% Kappa: 0.269

Epoch 5/7
----------

100%|██████████| 733/733 [00:43<00:00, 17.00it/s]

Train Loss: 1.3884 Acc: 36.95% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.89it/s]

Val Loss: 1.4023 Acc: 35.28% Kappa: 0.285

Epoch 6/7
----------

100%|██████████| 733/733 [00:45<00:00, 16.10it/s]

Train Loss: 1.3820 Acc: 37.62% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.72it/s]

Val Loss: 1.4006 Acc: 34.77% Kappa: 0.270

Epoch 7/7
----------

100%|██████████| 733/733 [00:42<00:00, 17.08it/s]

Train Loss: 1.3782 Acc: 37.69% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.73it/s]

Val Loss: 1.3994 Acc: 35.24% Kappa: 0.282

Training complete in 7m 5s
Best val Acc: 35.28%
Best val Kappa: 0.285
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp_manual_fc_only_best_exp3_epoch_5_kappa_0.285.jpg
Modelo guardado en: /kaggle/working/models/exp_manual_fc_only_best_exp3_20260430_162222.pth
Kappa exp7: 0.28459464283230507
Modelo: /kaggle/working/models/exp_manual_fc_only_best_exp3_20260430_162222.pth
Matriz: /kaggle/working/confusion_matrices/exp_manual_fc_only_best_exp3_epoch_5_kappa_0.285.jpg

### Experimento manual 2 — Solo FC con hiperparámetros del Experimento 1

En este experimento se utilizan los mejores hiperparámetros obtenidos en el Experimento 1 (optimización sobre la capa fully connected), pero se modifica el tamaño de batch a 16.

Configuración:

- capas entrenadas: solo `fc`
- batch size = 16
- learning rate ≈ 0.0022  
- momentum ≈ 0.908  
- epochs = 4  

El objetivo es evaluar si el cambio en el tamaño de batch mejora el desempeño del modelo cuando se entrena únicamente la capa final.

In [66]:
EXP_NAME = "exp_manual_fc_only_best_exp1_batch16"

BATCH_SIZE_EXP1_MANUAL = 16

train_ds_exp1m, val_ds_exp1m, train_dl_exp1m, val_dl_exp1m = create_dataloaders(
    new_train_directory,
    new_val_directory,
    BATCH_SIZE_EXP1_MANUAL,
    NUM_WORKERS
)

EXP1_LR = 0.002198906159202721
EXP1_MOMENTUM = 0.9079534063660759
EXP1_EPOCHS = 4

model = build_resnet50_model(
    num_classes=5,
    unfreeze_layer4=False,
    unfreeze_layer3=False
)

criterion = nn.CrossEntropyLoss()

model, kappa, history, model_path, cm_path = train_val(
    model,
    criterion,
    {"train": train_dl_exp1m, "val": val_dl_exp1m},
    {"train": train_ds_exp1m, "val": val_ds_exp1m},
    device,
    EXP1_EPOCHS,
    EXP1_LR,
    EXP1_MOMENTUM,
    EXP_NAME
)

results.append({
    "experiment": EXP_NAME,
    "trial": "manual_best_exp1",
    "batch_size": BATCH_SIZE_EXP1_MANUAL,
    "unfreeze_layer4": False,
    "unfreeze_layer3": False,
    "lr": EXP1_LR,
    "momentum": EXP1_MOMENTUM,
    "epochs": EXP1_EPOCHS,
    "kappa": kappa,
    "model_path": model_path,
    "cm_path": cm_path
})

all_histories.append(history)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)

print("Kappa manual exp1:", kappa)
print("Modelo:", model_path)
print("Matriz:", cm_path)

Epoch 0/3
----------

100%|██████████| 733/733 [00:42<00:00, 17.06it/s]

Train Loss: 1.4299 Acc: 33.38% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.53it/s]

Val Loss: 1.4089 Acc: 35.11% Kappa: 0.280

Epoch 1/3
----------

100%|██████████| 733/733 [00:42<00:00, 17.25it/s]

Train Loss: 1.3917 Acc: 36.91% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 20.02it/s]

Val Loss: 1.4157 Acc: 35.69% Kappa: 0.271

Epoch 2/3
----------

100%|██████████| 733/733 [00:45<00:00, 16.04it/s]

Train Loss: 1.3756 Acc: 37.97% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.83it/s]

Val Loss: 1.4228 Acc: 35.38% Kappa: 0.271

Epoch 3/3
----------

100%|██████████| 733/733 [00:42<00:00, 17.08it/s]

Train Loss: 1.3641 Acc: 39.15% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.77it/s]

Val Loss: 1.4328 Acc: 34.66% Kappa: 0.256

Training complete in 3m 32s
Best val Acc: 35.11%
Best val Kappa: 0.280
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp_manual_fc_only_best_exp1_batch16_epoch_0_kappa_0.280.jpg
Modelo guardado en: /kaggle/working/models/exp_manual_fc_only_best_exp1_batch16_20260430_162637.pth
Kappa manual exp1: 0.27982842402685393
Modelo: /kaggle/working/models/exp_manual_fc_only_best_exp1_batch16_20260430_162637.pth
Matriz: /kaggle/working/confusion_matrices/exp_manual_fc_only_best_exp1_batch16_epoch_0_kappa_0.280.jpg

### Experimento manual 3 — FC + layer4 con hiperparámetros del Experimento 3

En este experimento se reentrena manualmente la configuración más prometedora identificada por Optuna en el Experimento 3.

Configuración:

- capas entrenadas: `fc + layer4`
- batch size = 16
- learning rate ≈ 4.1e-4
- momentum ≈ 0.83
- epochs = 8

El objetivo es validar si la combinación óptima encontrada por Optuna se mantiene al repetir el entrenamiento de forma manual.

In [67]:
EXP_NAME = "exp_manual_fc_layer4_best_exp3_params_batch16"

BATCH_SIZE_EXP9 = 16

train_ds9, val_ds9, train_dl9, val_dl9 = create_dataloaders(
    new_train_directory,
    new_val_directory,
    BATCH_SIZE_EXP9,
    NUM_WORKERS
)

EXP9_LR = 4.1e-4
EXP9_MOMENTUM = 0.83
EXP9_EPOCHS = 8

model = build_resnet50_model(
    num_classes=5,
    unfreeze_layer4=True,
    unfreeze_layer3=False
)

criterion = nn.CrossEntropyLoss()

model, kappa, history, model_path, cm_path = train_val(
    model,
    criterion,
    {"train": train_dl9, "val": val_dl9},
    {"train": train_ds9, "val": val_ds9},
    device,
    EXP9_EPOCHS,
    EXP9_LR,
    EXP9_MOMENTUM,
    EXP_NAME
)

results.append({
    "experiment": EXP_NAME,
    "trial": "manual_best_exp3_params",
    "batch_size": BATCH_SIZE_EXP9,
    "unfreeze_layer4": True,
    "unfreeze_layer3": False,
    "lr": EXP9_LR,
    "momentum": EXP9_MOMENTUM,
    "epochs": EXP9_EPOCHS,
    "kappa": kappa,
    "model_path": model_path,
    "cm_path": cm_path
})

all_histories.append(history)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)

print("Kappa exp9:", kappa)
print("Modelo:", model_path)
print("Matriz:", cm_path)

Epoch 0/7
----------

100%|██████████| 733/733 [00:54<00:00, 13.56it/s]

Train Loss: 1.4588 Acc: 32.19% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.88it/s]

Val Loss: 1.4202 Acc: 34.15% Kappa: 0.242

Epoch 1/7
----------

100%|██████████| 733/733 [00:52<00:00, 13.88it/s]

Train Loss: 1.4116 Acc: 35.20% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.62it/s]

Val Loss: 1.4072 Acc: 35.18% Kappa: 0.256

Epoch 2/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.77it/s]

Train Loss: 1.3953 Acc: 36.61% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.72it/s]

Val Loss: 1.4050 Acc: 34.46% Kappa: 0.268

Epoch 3/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.82it/s]

Train Loss: 1.3889 Acc: 36.73% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.81it/s]

Val Loss: 1.3983 Acc: 34.90% Kappa: 0.266

Epoch 4/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.78it/s]

Train Loss: 1.3789 Acc: 38.35% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.86it/s]

Val Loss: 1.3971 Acc: 35.82% Kappa: 0.283

Epoch 5/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.77it/s]

Train Loss: 1.3732 Acc: 38.27% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.81it/s]

Val Loss: 1.3982 Acc: 34.90% Kappa: 0.277

Epoch 6/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.76it/s]

Train Loss: 1.3631 Acc: 39.07% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.78it/s]

Val Loss: 1.3952 Acc: 35.93% Kappa: 0.288

Epoch 7/7
----------

100%|██████████| 733/733 [00:53<00:00, 13.76it/s]

Train Loss: 1.3559 Acc: 39.41% Kappa: nan

100%|██████████| 184/184 [00:09<00:00, 19.87it/s]

Val Loss: 1.3945 Acc: 35.72% Kappa: 0.289

Training complete in 8m 22s
Best val Acc: 35.72%
Best val Kappa: 0.289
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp_manual_fc_layer4_best_exp3_params_batch16_epoch_7_kappa_0.289.jpg
Modelo guardado en: /kaggle/working/models/exp_manual_fc_layer4_best_exp3_params_batch16_20260430_163515.pth
Kappa exp9: 0.28945729465652004
Modelo: /kaggle/working/models/exp_manual_fc_layer4_best_exp3_params_batch16_20260430_163515.pth
Matriz: /kaggle/working/confusion_matrices/exp_manual_fc_layer4_best_exp3_params_batch16_epoch_7_kappa_0.289.jpg

### Experimento manual 4 — FC + layer4 con hiperparámetros del Experimento 1 (batch 32)

En este experimento se evalúa la combinación de:

- fine-tuning de `layer4`;
- hiperparámetros óptimos del Experimento 1;
- batch size = 32.

Configuración:

- capas entrenadas: `fc + layer4`
- batch size = 32
- learning rate ≈ 0.0022  
- momentum ≈ 0.908  
- epochs = 4  

El objetivo es analizar si los hiperparámetros que funcionaron bien en un esquema sin fine-tuning (Experimento 1) también son efectivos cuando se entrenan capas profundas.

In [68]:
EXP_NAME = "exp_manual_fc_layer4_best_exp1_params_batch32"

BATCH_SIZE_EXP10 = 32

train_ds10, val_ds10, train_dl10, val_dl10 = create_dataloaders(
    new_train_directory,
    new_val_directory,
    BATCH_SIZE_EXP10,
    NUM_WORKERS
)

EXP10_LR = 0.002198906159202721
EXP10_MOMENTUM = 0.9079534063660759
EXP10_EPOCHS = 4

model = build_resnet50_model(
    num_classes=5,
    unfreeze_layer4=True,
    unfreeze_layer3=False
)

criterion = nn.CrossEntropyLoss()

model, kappa, history, model_path, cm_path = train_val(
    model,
    criterion,
    {"train": train_dl10, "val": val_dl10},
    {"train": train_ds10, "val": val_ds10},
    device,
    EXP10_EPOCHS,
    EXP10_LR,
    EXP10_MOMENTUM,
    EXP_NAME
)

results.append({
    "experiment": EXP_NAME,
    "trial": "manual_best_exp1_params",
    "batch_size": BATCH_SIZE_EXP10,
    "unfreeze_layer4": True,
    "unfreeze_layer3": False,
    "lr": EXP10_LR,
    "momentum": EXP10_MOMENTUM,
    "epochs": EXP10_EPOCHS,
    "kappa": kappa,
    "model_path": model_path,
    "cm_path": cm_path
})

all_histories.append(history)

pd.DataFrame(results).to_csv(f"/kaggle/working/{EXP_NAME}_results.csv", index=False)

print("Kappa exp10:", kappa)
print("Modelo:", model_path)
print("Matriz:", cm_path)

Epoch 0/3
----------

100%|██████████| 367/367 [00:51<00:00,  7.11it/s]

Train Loss: 1.4244 Acc: 34.12% Kappa: nan

100%|██████████| 92/92 [00:09<00:00, 10.07it/s]

Val Loss: 1.4115 Acc: 34.05% Kappa: 0.245

Epoch 1/3
----------

100%|██████████| 367/367 [00:51<00:00,  7.16it/s]

Train Loss: 1.3727 Acc: 38.55% Kappa: nan

100%|██████████| 92/92 [00:09<00:00, 10.13it/s]

Val Loss: 1.4012 Acc: 35.24% Kappa: 0.287

Epoch 2/3
----------

100%|██████████| 367/367 [00:51<00:00,  7.16it/s]

Train Loss: 1.3421 Acc: 40.00% Kappa: nan

100%|██████████| 92/92 [00:09<00:00, 10.18it/s]

Val Loss: 1.4125 Acc: 34.15% Kappa: 0.264

Epoch 3/3
----------

100%|██████████| 367/367 [00:51<00:00,  7.19it/s]

Train Loss: 1.3096 Acc: 42.58% Kappa: nan

100%|██████████| 92/92 [00:09<00:00,  9.96it/s]

Val Loss: 1.4233 Acc: 36.40% Kappa: 0.301

Training complete in 4m 3s
Best val Acc: 36.40%
Best val Kappa: 0.301
Best confusion matrix saved at: /kaggle/working/confusion_matrices/exp_manual_fc_layer4_best_exp1_params_batch32_epoch_3_kappa_0.301.jpg
Modelo guardado en: /kaggle/working/models/exp_manual_fc_layer4_best_exp1_params_batch32_20260430_163922.pth
Kappa exp10: 0.3005762337678446
Modelo: /kaggle/working/models/exp_manual_fc_layer4_best_exp1_params_batch32_20260430_163922.pth
Matriz: /kaggle/working/confusion_matrices/exp_manual_fc_layer4_best_exp1_params_batch32_epoch_3_kappa_0.301.jpg